Particle Identification and Tracking: testing/accum_case_test.cpp File Reference
accum_case_test.cpp File Reference
#include <iostream>
#include <string>
#include "accum_case.h"
#include "accum_chi4_self.h"
Functions
float w (float x, float l)
int main (int argc, const char *argv[])
Function Documentation
int main (int argc, const char * argv[])
References utilities::Accum_case::fill(), and w().
float w (float x, float l)
Referenced by main().