Particle Identification and Tracking: testing/add_to_hdf_test.cpp File Reference
add_to_hdf_test.cpp File Reference
#include <iostream>
#include "master_box_t.h"
#include "particle_base.h"
#include "hash_case.h"
#include "wrapper_i_hdf.h"
#include "wrapper_o_hdf.h"
#include "filter.h"
Functions
int main (int argc, const char *argv[])
Function Documentation
int main (int argc, const char * argv[])
References utilities::D_INDEX, utilities::D_XPOS, utilities::D_YPOS, fname, utilities::Wrapper_i_hdf::get_dims(), utilities::Wrapper_i_hdf::get_num_frames(), tracking::hash_case::init(), tracking::Master_box::init(), utilities::Wrapper_i_hdf::initialize(), tracking::hash_case::output_to_wrapper(), and tracking::Master_box::size().