Particle Identification and Tracking: tracking::Trk_accumulator Class Reference
tracking::Trk_accumulator Class Reference abstract
An abstract base class for track accumulator computations.
#include <track_accum.h>
Public Member Functions
virtual void add_disp (const utilities::Tuplef &displacement, unsigned steps)=0
Add a track segment displacement.
virtual unsigned max_step () const =0
Returns the maximum step that the accumulator can deal with.
virtual ~Trk_accumulator ()
destructor
Detailed Description
An abstract base class for track accumulator computations.
That is computations that only care about displacement values and the time step between them, with out worrying about correlations with in tracks or anything about the spatial correlations of the particles.
Constructor & Destructor Documentation
virtual tracking::Trk_accumulator::~Trk_accumulator () inline virtual
destructor
Member Function Documentation
virtual void tracking::Trk_accumulator::add_disp (const utilities::Tuplef & displacement, unsigned steps) pure virtual
Add a track segment displacement.
Parameters
[in] displacement The net displacement of the track segment.
[in] steps The number of time steps in the track segment.
Implemented in tracking::TA_msd, tracking::TA_theta_rlim, tracking::TA_disp, and tracking::TA_vanHove.
Referenced by tracking::Track_shelf::compute_corrected_TA(), and tracking::Track_shelf::compute_corrected_TA_ncuts().
virtual unsigned tracking::Trk_accumulator::max_step () const pure virtual
Returns the maximum step that the accumulator can deal with.
Implemented in tracking::TA_msd, tracking::TA_theta_rlim, tracking::TA_disp, and tracking::TA_vanHove.
Referenced by tracking::Track_shelf::compute_corrected_TA(), and tracking::Track_shelf::compute_corrected_TA_ncuts().
The documentation for this class was generated from the following file:
common_src/include/track_accum.h