Particle Identification and Tracking: utilities::Wrapper_in Class Reference
utilities::Wrapper_in Class Reference abstract
A mostly abstract base class for input wrappers.
#include <wrapper_i.h>
Public Member Functions
virtual int get_value (int &out, int ind, D_TYPE type, int frame) const =0
Returns the value of the type specified from the particle selected.
virtual float get_value (float &out, int ind, D_TYPE type, int frame) const =0
Returns the value of the type specified from the particle selected.
virtual std::complex< float > get_value (std::complex< float > &out, int ind, D_TYPE type, int frame) const =0
Returns the value of the type specified from the particle selected.
virtual std::set< D_TYPE > get_data_types () const =0
Returns a set of the data types.
virtual int get_num_entries (unsigned int frame) const =0
Return the number of entries the specified frame.
virtual int get_num_entries () const =0
Return the total number of entries in the wrapper.
virtual int get_num_frames () const =0
Return the number of frames.
virtual bool contains_type (D_TYPE type) const =0
Returns if the wrapper contains the specified data type.
virtual Tuplef get_dims () const =0
Returns the dimension of each 'frame' of the data in the wrapper.
virtual ~Wrapper_in ()
Wrapper_in ()
Meta data handling functions
const Md_store * get_Md_store (unsigned int j) const
Returns a pointer to plane j's meta data store.
Md_store * get_Md_store (unsigned int j)
Returns a pointer to plane j's meta data store.
void set_Md_store (unsigned int j, Md_store *in)
Sets the Md_store for plane j.
void set_Md_store_size (unsigned int j)
Sets the size of the md_stores_ vector.
unsigned int get_Md_store_size ()
Gets the size of the md_stores_ vector.
void clear_Md_store (unsigned int j)
Deletes plane j's Md_store.
Private Attributes
std::vector< Md_store * > md_stores_
Detailed Description
A mostly abstract base class for input wrappers.
Has handling for Md_store at this level
Constructor & Destructor Documentation
Wrapper_in::~Wrapper_in () virtual
References md_stores_.
Wrapper_in::Wrapper_in ()
Member Function Documentation
void Wrapper_in::clear_Md_store (unsigned int j)
Deletes plane j's Md_store.
References md_stores_.
virtual bool utilities::Wrapper_in::contains_type (D_TYPE type) const pure virtual
Returns if the wrapper contains the specified data type.
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, iden::Wrapper_i_plu, utilities::Wrapper_i_file, utilities::Wrapper_i_dummy, and utilities::Wrapper_i_dummy.
virtual std::set<D_TYPE> utilities::Wrapper_in::get_data_types () const pure virtual
Returns a set of the data types.
Use the other version
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, iden::Wrapper_i_plu, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, utilities::Wrapper_i_file, utilities::Wrapper_i_dummy, and utilities::Wrapper_i_dummy.
Referenced by tracking::hash_case::init(), and tracking::Master_box::priv_init().
virtual Tuplef utilities::Wrapper_in::get_dims () const pure virtual
Returns the dimension of each 'frame' of the data in the wrapper.
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, utilities::Wrapper_i_dummy, iden::Wrapper_i_plu, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, utilities::Wrapper_i_file, utilities::Wrapper_i_dummy, and utilities::Wrapper_i_dummy.
Referenced by tracking::hash_case::init().
const Md_store * Wrapper_in::get_Md_store (unsigned int j) const
Returns a pointer to plane j's meta data store.
Const version
References md_stores_.
Referenced by tracking::Master_box::get_Md_store(), and tracking::hash_case::init().
Md_store * Wrapper_in::get_Md_store (unsigned int j)
Returns a pointer to plane j's meta data store.
Const version
References md_stores_.
unsigned int Wrapper_in::get_Md_store_size ()
Gets the size of the md_stores_ vector.
References md_stores_.
virtual int utilities::Wrapper_in::get_num_entries (unsigned int frame) const pure virtual
Return the number of entries the specified frame.
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, and iden::Wrapper_i_plu.
Referenced by tracking::hash_case::init(), and tracking::Master_box::priv_init().
virtual int utilities::Wrapper_in::get_num_entries () const pure virtual
Return the total number of entries in the wrapper.
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, and iden::Wrapper_i_plu.
virtual int utilities::Wrapper_in::get_num_frames () const pure virtual
Return the number of frames.
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, iden::Wrapper_i_plu, utilities::Wrapper_i_file, utilities::Wrapper_i_dummy, and utilities::Wrapper_i_dummy.
Referenced by tracking::hash_case::init(), and tracking::Master_box::priv_init().
virtual int utilities::Wrapper_in::get_value (int & out, int ind, D_TYPE type, int frame) const pure virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, iden::Wrapper_i_plu, utilities::Wrapper_i_file, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, and utilities::Wrapper_i_dummy.
Referenced by tracking::particle_base::fill_position(), tracking::particle_base::get_value(), tracking::particle_base::get_wrapper_value(), tracking::hash_case::init(), utilities::Filter_ers::operator()(), and utilities::Filter_ersI::operator()().
virtual float utilities::Wrapper_in::get_value (float & out, int ind, D_TYPE type, int frame) const pure virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, utilities::Wrapper_i_dummy, iden::Wrapper_i_plu, utilities::Wrapper_i_file, utilities::Wrapper_i_dummy, and utilities::Wrapper_i_dummy.
virtual std::complex<float> utilities::Wrapper_in::get_value (std::complex< float > & out, int ind, D_TYPE type, int frame) const pure virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, iden::Wrapper_i_plu, utilities::Wrapper_i_file, utilities::Wrapper_i_dummy, and utilities::Wrapper_i_dummy.
void Wrapper_in::set_Md_store (unsigned int j, Md_store * in)
Sets the Md_store for plane j.
When the pointer is assigned the wrapper takes ownership of the pointer and will clean it up.
References md_stores_.
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), main(), utilities::Wrapper_i_hdf::priv_init(), and iden::Iden::process_frame().
void Wrapper_in::set_Md_store_size (unsigned int j)
Sets the size of the md_stores_ vector.
References md_stores_.
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), main(), utilities::Wrapper_i_hdf::priv_init(), and iden::Wrapper_i_plu::Wrapper_i_plu().
Member Data Documentation
std::vector<Md_store*> utilities::Wrapper_in::md_stores_ private
Referenced by clear_Md_store(), get_Md_store(), get_Md_store_size(), set_Md_store(), set_Md_store_size(), and ~Wrapper_in().
The documentation for this class was generated from the following files:
common_src/include/wrapper_i.h
common_src/cxx/wrapper_i.cpp