Particle Identification and Tracking: utilities::Wrapper_i_file Class Reference
utilities::Wrapper_i_file Class Reference abstract
Wrapper class for dealing with data from a text file.
#include <wrapper_i_file.h>
Public Member Functions
int get_value (int &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
float get_value (float &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::complex< float > get_value (std::complex< float > &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::set< D_TYPE > get_data_types () const
Returns a set of the data types.
int get_num_entries (int frame) const
int get_num_frames () const
Return the number of frames.
bool contains_type (D_TYPE type) const
Returns if the wrapper contains the specified data type.
Tuple get_dims () const
Returns the dimension of each 'frame' of the data in the wrapper.
~Wrapper_i_file ()
Wrapper_i_file (const std::string &fname, const std::set< utilities::D_TYPE > &dtypes, int rows, const std::vector< int > &frame_edges)
virtual int get_num_entries (unsigned int frame) const =0
Return the number of entries the specified frame.
virtual int get_num_entries () const =0
Return the total number of entries in the wrapper.
Meta data handling functions
const Md_store * get_Md_store (unsigned int j) const
Returns a pointer to plane j's meta data store.
Md_store * get_Md_store (unsigned int j)
Returns a pointer to plane j's meta data store.
void set_Md_store (unsigned int j, Md_store *in)
Sets the Md_store for plane j.
void set_Md_store_size (unsigned int j)
Sets the size of the md_stores_ vector.
unsigned int get_Md_store_size ()
Gets the size of the md_stores_ vector.
void clear_Md_store (unsigned int j)
Deletes plane j's Md_store.
Protected Member Functions
void fill_data (std:string file_name, int row, int col)
Protected Attributes
int rows
number of rows(particles) that the
int cols
map< utilities::D_TYPE, int > contents
vector< int > frame_edges_
Private Member Functions
double get_value (int ind, utilities::D_TYPE type) const
Private Attributes
double * first
Pointer to the first data point of the.
Detailed Description
Wrapper class for dealing with data from a text file.
This is mainly for testing purposes.
This class is broken.
Constructor & Destructor Documentation
utilities::Wrapper_i_file::~Wrapper_i_file ()
utilities::Wrapper_i_file::Wrapper_i_file (const std::string & fname, const std::set< utilities::D_TYPE > & dtypes, int rows, const std::vector< int > & frame_edges)
Member Function Documentation
void Wrapper_in::clear_Md_store (unsigned int j) inherited
Deletes plane j's Md_store.
References utilities::Wrapper_in::md_stores_.
bool utilities::Wrapper_i_file::contains_type (D_TYPE type) const virtual
Returns if the wrapper contains the specified data type.
Implements utilities::Wrapper_in.
void utilities::Wrapper_i_file::fill_data (std:string file_name, int row, int col) protected
std::set<D_TYPE> utilities::Wrapper_i_file::get_data_types () const virtual
Returns a set of the data types.
Use the other version
Implements utilities::Wrapper_in.
Tuple utilities::Wrapper_i_file::get_dims () const virtual
Returns the dimension of each 'frame' of the data in the wrapper.
Implements utilities::Wrapper_in.
const Md_store * Wrapper_in::get_Md_store (unsigned int j) const inherited
Returns a pointer to plane j's meta data store.
Const version
References utilities::Wrapper_in::md_stores_.
Referenced by tracking::Master_box::get_Md_store(), and tracking::hash_case::init().
Md_store * Wrapper_in::get_Md_store (unsigned int j) inherited
Returns a pointer to plane j's meta data store.
Const version
References utilities::Wrapper_in::md_stores_.
unsigned int Wrapper_in::get_Md_store_size () inherited
Gets the size of the md_stores_ vector.
References utilities::Wrapper_in::md_stores_.
int utilities::Wrapper_i_file::get_num_entries (int frame) const
virtual int utilities::Wrapper_in::get_num_entries (unsigned int frame) const pure virtual inherited
Return the number of entries the specified frame.
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, and iden::Wrapper_i_plu.
Referenced by tracking::hash_case::init(), and tracking::Master_box::priv_init().
virtual int utilities::Wrapper_in::get_num_entries () const pure virtual inherited
Return the total number of entries in the wrapper.
Implemented in utilities::Wrapper_i_generic, utilities::Wrapper_i_hdf, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, utilities::Wrapper_i_jb_binary, utilities::Wrapper_i_dummy, utilities::Wrapper_i_dummy, and iden::Wrapper_i_plu.
int utilities::Wrapper_i_file::get_num_frames () const virtual
Return the number of frames.
Implements utilities::Wrapper_in.
double utilities::Wrapper_i_file::get_value (int ind, utilities::D_TYPE type) const private
int utilities::Wrapper_i_file::get_value (int & out, int ind, D_TYPE type, int frame) const virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
float utilities::Wrapper_i_file::get_value (float & out, int ind, D_TYPE type, int frame) const virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
std::complex<float> utilities::Wrapper_i_file::get_value (std::complex< float > & out, int ind, D_TYPE type, int frame) const virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
void Wrapper_in::set_Md_store (unsigned int j, Md_store * in) inherited
Sets the Md_store for plane j.
When the pointer is assigned the wrapper takes ownership of the pointer and will clean it up.
References utilities::Wrapper_in::md_stores_.
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), main(), utilities::Wrapper_i_hdf::priv_init(), and iden::Iden::process_frame().
void Wrapper_in::set_Md_store_size (unsigned int j) inherited
Sets the size of the md_stores_ vector.
References utilities::Wrapper_in::md_stores_.
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), main(), utilities::Wrapper_i_hdf::priv_init(), and iden::Wrapper_i_plu::Wrapper_i_plu().
Member Data Documentation
int utilities::Wrapper_i_file::cols protected
map<utilities::D_TYPE, int> utilities::Wrapper_i_file::contents protected
double* utilities::Wrapper_i_file::first private
Pointer to the first data point of the.
vector<int> utilities::Wrapper_i_file::frame_edges_ protected
int utilities::Wrapper_i_file::rows protected
number of rows(particles) that the
The documentation for this class was generated from the following file:
common_src/include/wrapper_i_file.h