Particle Identification and Tracking: tracking::TA_theta_rlim Class Reference
tracking::TA_theta_rlim Class Reference
Track accumulator that computes the distribution of displacement direction for displacements with in the given range of displacement magnitudes.
#include <ta_theta_rlim.h>
Public Member Functions
void add_disp (const utilities::Tuplef &theta_rlimlacement, unsigned steps)
Add a track segment displacement.
unsigned max_step () const
Returns the maximum step that the accumulator can deal with.
TA_theta_rlim (unsigned max_step, unsigned t_nbins, float min_r, float max_r)
Constructor.
~TA_theta_rlim ()
Destructor.
void output_to_wrapper (utilities::Generic_wrapper &out, const utilities::Md_store &md_store) const
Output function.
Private Attributes
std::vector< utilities::Histogram > theta_
A vector of histograms for.
unsigned max_step_
Maximum time step.
float min_r_sqr_
minimum length squared displacements to contribute to the histogram
float max_r_sqr_
maximum length squared displacements to contribute to the histogram
Detailed Description
Track accumulator that computes the distribution of displacement direction for displacements with in the given range of displacement magnitudes.
Constructor & Destructor Documentation
TA_theta_rlim::TA_theta_rlim (unsigned max_step, unsigned t_nbins, float min_r, float max_r)
Constructor.
TA_theta_rlim::~TA_theta_rlim ()
Destructor.
Member Function Documentation
void TA_theta_rlim::add_disp (const utilities::Tuplef & displacement, unsigned steps) virtual
Add a track segment displacement.
Parameters
[in] displacement The net displacement of the track segment.
[in] steps The number of time steps in the track segment.
Implements tracking::Trk_accumulator.
References max_step_, min_r_sqr_, and theta_.
unsigned tracking::TA_theta_rlim::max_step () const inline virtual
Returns the maximum step that the accumulator can deal with.
Implements tracking::Trk_accumulator.
References max_step_.
void TA_theta_rlim::output_to_wrapper (utilities::Generic_wrapper & out, const utilities::Md_store & md_store) const
Output function.
References utilities::Generic_wrapper::add_meta_data(), base_name, utilities::Generic_wrapper::close_group(), utilities::Generic_wrapper::close_wrapper(), utilities::format_name(), utilities::Md_store::get_value(), utilities::Generic_wrapper::is_open(), max_step_, utilities::Generic_wrapper::open_group(), utilities::Generic_wrapper::open_wrapper(), and theta_.
Member Data Documentation
float tracking::TA_theta_rlim::max_r_sqr_ private
maximum length squared displacements to contribute to the histogram
unsigned tracking::TA_theta_rlim::max_step_ private
Maximum time step.
Referenced by add_disp(), max_step(), and output_to_wrapper().
float tracking::TA_theta_rlim::min_r_sqr_ private
minimum length squared displacements to contribute to the histogram
Referenced by add_disp().
std::vector<utilities::Histogram> tracking::TA_theta_rlim::theta_ private
A vector of histograms for.
Referenced by add_disp(), and output_to_wrapper().
The documentation for this class was generated from the following files:
common_src/include/ta_theta_rlim.h
common_src/cxx/ta_theta_rlim.cpp