Particle Identification and Tracking: utilities::Filter Class Reference
utilities::Filter Class Reference abstract
ABC for filter objects.
#include <filter.h>
Public Member Functions
virtual bool operator() (int index, int frame) const =0
Returns true if the particle at index in frame passes what every criteria that the subclasses implement.
virtual void set_wrapper (const Wrapper_in *)=0
Sets pointer to Wrapper_in to read data from.
virtual FILT_TYPE get_type () const =0
Returns filter type.
virtual ~Filter ()
Destructor.
Filter ()
Empty constructor.
Detailed Description
ABC for filter objects.
Filter objects act as a (partial) layer on top of the wrapper objects to allow only particles that meet criteria to even be created. There are probably better ways to factor this code.
They take in a the index and frame of particle in a returns a bool, true if the particle is good, false if it is bad.
Constructor & Destructor Documentation
virtual utilities::Filter::~Filter () inline virtual
Destructor.
utilities::Filter::Filter () inline
Empty constructor.
Member Function Documentation
virtual FILT_TYPE utilities::Filter::get_type () const pure virtual
Returns filter type.
Implemented in utilities::Filter_ersI, utilities::Filter_ers, and utilities::Filter_trivial.
Referenced by main().
virtual bool utilities::Filter::operator() (int index, int frame) const pure virtual
Returns true if the particle at index in frame passes what every criteria that the subclasses implement.
Implemented in utilities::Filter_ersI, utilities::Filter_ers, and utilities::Filter_trivial.
virtual void utilities::Filter::set_wrapper (const Wrapper_in *) pure virtual
Sets pointer to Wrapper_in to read data from.
Implemented in utilities::Filter_ersI, utilities::Filter_ers, and utilities::Filter_trivial.
Referenced by tracking::hash_case::init(), and tracking::Master_box::init().
The documentation for this class was generated from the following file:
common_src/include/filter.h