Particle Identification and Tracking: tracking::Corr_case Class Reference
tracking::Corr_case Class Reference
A class to hold a stack of Corr objects for handing into a hash_case.
#include <corr_case.h>
Public Member Functions
Corr_case (const tracking::Corr_gofr *, int comp_count, float max_range, const int n_bins, int comp_num, int dset_num, int read_comp_num)
Constructor for filling with Corr_gofr.
void out_to_wrapper (utilities::Generic_wrapper &wrap, const std::string &base_name, const utilities::Md_store *md_store) const
Averages the values in a vector of Accum_sofq and writes.
tracking::Corr * at (int j)
Returns the nth element of the case.
tracking::Corr * operator[] (int j)
Returns the nth element of the case.
unsigned int size () const
Returns size.
~Corr_case ()
Destructor.
Private Attributes
std::vector< tracking::Corr * > corr_vec_
Vector of correlation objects.
std::map< std::string, float > prams_float_
map of float parameters fed to the corr objects
std::map< std::string,int > prams_int_
map of integer parameters fed to the corr objects
Detailed Description
A class to hold a stack of Corr objects for handing into a hash_case.
Very similar to Accum_case. These are not the most elegant solutions, but they seem to work.
Constructor & Destructor Documentation
Corr_case::Corr_case (const tracking::Corr_gofr * , int comp_count, float max_range, const int n_bins, int comp_num, int dset_num, int read_comp_num)
Constructor for filling with Corr_gofr.
The pointer does nothing, but is passed into set the type.
References corr_vec_, prams_float_, and prams_int_.
Corr_case::~Corr_case ()
Destructor.
References corr_vec_.
Member Function Documentation
tracking::Corr* tracking::Corr_case::at (int j) inline
Returns the nth element of the case.
Will throw out of range errors
References corr_vec_.
tracking::Corr* tracking::Corr_case::operator[] (int j) inline
Returns the nth element of the case.
Will not throw out of range errors
References corr_vec_.
void Corr_case::out_to_wrapper (utilities::Generic_wrapper & wrap, const std::string & base_name, const utilities::Md_store * md_store) const
Averages the values in a vector of Accum_sofq and writes.
References utilities::Generic_wrapper::add_meta_data(), utilities::Generic_wrapper::close_group(), utilities::Generic_wrapper::close_wrapper(), corr_vec_, utilities::format_name(), utilities::Generic_wrapper::open_group(), utilities::Generic_wrapper::open_wrapper(), prams_float_, and prams_int_.
Referenced by main().
unsigned int tracking::Corr_case::size () const inline
Returns size.
References corr_vec_.
Referenced by tracking::hash_case::compute_corr().
Member Data Documentation
std::vector< tracking::Corr*> tracking::Corr_case::corr_vec_ private
Vector of correlation objects.
Referenced by at(), Corr_case(), operator[](), out_to_wrapper(), size(), and ~Corr_case().
std::map<std::string,float> tracking::Corr_case::prams_float_ private
map of float parameters fed to the corr objects
Referenced by Corr_case(), and out_to_wrapper().
std::map<std::string ,int> tracking::Corr_case::prams_int_ private
map of integer parameters fed to the corr objects
Referenced by Corr_case(), and out_to_wrapper().
The documentation for this class was generated from the following files:
common_src/include/corr_case.h
common_src/cxx/corr_case.cpp