Particle Identification and Tracking: tracking::Corr Class Reference
tracking::Corr Class Reference abstract
A mostly ABC of objects that can be handed into hash_case and calculates correlation functions.
#include <corr.h>
Public Member Functions
virtual void compute (const particle *, const std::vector< const particle * > &)=0
takes in a particle_base object.
virtual void out_to_wrapper (utilities::Generic_wrapper &, const std::string &, const utilities::Md_store *) const =0
outputs the result of the computation to the wrapper
virtual float get_max_range () const =0
returns the maximum range that the Corr object looks out to.
void add_plane_temperature (float temp)
Adds the temperature for a plane.
virtual ~Corr ()
Destructor.
Protected Member Functions
Corr ()
Protected Attributes
float temperature_sum_
The sum of the temperatures added.
unsigned int plane_count_
Count of the number of planes added.
Detailed Description
A mostly ABC of objects that can be handed into hash_case and calculates correlation functions.
This class deals with temperature meta-data
Constructor & Destructor Documentation
virtual tracking::Corr::~Corr () inline virtual
Destructor.
Corr::Corr () protected
Member Function Documentation
void Corr::add_plane_temperature (float temp)
Adds the temperature for a plane.
References plane_count_, and temperature_sum_.
Referenced by tracking::Hash_shelf::compute_corr().
virtual void tracking::Corr::compute (const particle * , const std::vector< const particle * > &) pure virtual
takes in a particle_base object.
For correlations that need the tracking information this should throw an error or something clever like that
Implemented in tracking::Dummy_corr, tracking::Corr_pair_diffusion, tracking::Corr_theta_2pt, tracking::Corr_gofr, and tracking::Corr_goftheta.
Referenced by tracking::hash_box::compute_corr().
virtual float tracking::Corr::get_max_range () const pure virtual
returns the maximum range that the Corr object looks out to.
This is needed so that the Hash_shelf can properly limit the particles that it hands in
Implemented in tracking::Dummy_corr, tracking::Corr_pair_diffusion, tracking::Corr_gofr, tracking::Corr_goftheta, and tracking::Corr_theta_2pt.
Referenced by tracking::hash_box::compute_corr(), and tracking::Hash_shelf::compute_corr().
virtual void tracking::Corr::out_to_wrapper (utilities::Generic_wrapper & , const std::string & , const utilities::Md_store *) const pure virtual
outputs the result of the computation to the wrapper
Implemented in tracking::Dummy_corr, tracking::Corr_pair_diffusion, tracking::Corr_theta_2pt, and tracking::Corr_gofr.
Member Data Documentation
unsigned int tracking::Corr::plane_count_ protected
Count of the number of planes added.
Referenced by add_plane_temperature(), tracking::Corr_gofr::out_to_wrapper(), and tracking::Corr_theta_2pt::out_to_wrapper().
float tracking::Corr::temperature_sum_ protected
The sum of the temperatures added.
Referenced by add_plane_temperature(), tracking::Corr_gofr::out_to_wrapper(), and tracking::Corr_theta_2pt::out_to_wrapper().
The documentation for this class was generated from the following files:
common_src/include/corr.h
common_src/cxx/corr.cpp