Particle Identification and Tracking: tracking::TA_vanHove Class Reference
tracking::TA_vanHove Class Reference
Track accumulator that implements computation of van Hove functions.
#include <ta_vanHove.h>
Public Member Functions
void add_disp (const utilities::Tuplef &displacement, unsigned steps)
Add a track segment displacement.
unsigned max_step () const
Returns the maximum step that the accumulator can deal with.
TA_vanHove (unsigned max_steps, unsigned nbins, float max_range)
Constructor.
virtual ~TA_vanHove ()
Destructor.
void output_to_wrapper (utilities::Generic_wrapper &out, const utilities::Md_store &md_store) const
Output function.
Private Attributes
std::vector< utilities::Histogram > x_disp_
vector of Histogram objects, one for each time step, for displacement along x.
std::vector< utilities::Histogram > y_disp_
vector of Histogram objects, one for each time step, for displacement along y.
unsigned max_step_
Maximum time step.
Detailed Description
Track accumulator that implements computation of van Hove functions.
Constructor & Destructor Documentation
TA_vanHove::TA_vanHove (unsigned max_steps, unsigned nbins, float max_range)
Constructor.
TA_vanHove::~TA_vanHove () virtual
Destructor.
Member Function Documentation
void TA_vanHove::add_disp (const utilities::Tuplef & displacement, unsigned steps) virtual
Add a track segment displacement.
Parameters
[in] displacement The net displacement of the track segment.
[in] steps The number of time steps in the track segment.
Implements tracking::Trk_accumulator.
References max_step_, x_disp_, and y_disp_.
unsigned tracking::TA_vanHove::max_step () const inline virtual
Returns the maximum step that the accumulator can deal with.
Implements tracking::Trk_accumulator.
References max_step_.
void TA_vanHove::output_to_wrapper (utilities::Generic_wrapper & out, const utilities::Md_store & md_store) const
Output function.
References utilities::Generic_wrapper::add_meta_data(), base_name, utilities::Generic_wrapper::close_group(), utilities::Generic_wrapper::close_wrapper(), utilities::format_name(), utilities::Md_store::get_value(), utilities::Generic_wrapper::is_open(), max_step_, utilities::Generic_wrapper::open_group(), utilities::Generic_wrapper::open_wrapper(), x_disp_, and y_disp_.
Referenced by main().
Member Data Documentation
unsigned tracking::TA_vanHove::max_step_ private
Maximum time step.
Referenced by add_disp(), max_step(), and output_to_wrapper().
std::vector<utilities::Histogram> tracking::TA_vanHove::x_disp_ private
vector of Histogram objects, one for each time step, for displacement along x.
Referenced by add_disp(), and output_to_wrapper().
std::vector<utilities::Histogram> tracking::TA_vanHove::y_disp_ private
vector of Histogram objects, one for each time step, for displacement along y.
Referenced by add_disp(), and output_to_wrapper().
The documentation for this class was generated from the following files:
common_src/include/ta_vanHove.h
common_src/cxx/ta_vanHove.cpp