Particle Identification and Tracking: iden::Image_series Class Reference
iden::Image_series Class Reference
#include <image_series.h>
Public Member Functions
Image_series ()
~Image_series ()
void select_plane (unsigned int plane)
Set the plane w.
const void * get_plane_pixels () const
Returns the data of the current plane.
utilities::Md_store * get_plane_md (const MD_parser &parser) const
Returns the current plane's meta data.
utilities::Tuple< unsigned int, 2 > get_plane_dims () const
Returns the plane dimensions.
WORD get_scan_step () const
returns the plane scan_step
int get_frame_count () const
Returns the number of planes in the image.
bool init (const std::string &base_name)
PIX_TYPE get_pixel_type () const
Returns the size of the image pixels.
Private Member Functions
bool to_grey ()
Converts the image to 8 bit grey scale.
Private Attributes
std::string basename_
std::string dirname_
unsigned int cur_plane_
bool image_open_
fipImage image_
unsigned int padding_
unsigned int planecount_
PIX_TYPE pix_type_
Constructor & Destructor Documentation
Image_series::Image_series ()
Image_series::~Image_series ()
References image_.
Member Function Documentation
int Image_series::get_frame_count () const virtual
Returns the number of planes in the image.
Implements iden::Image_base.
References planecount_.
Referenced by main().
iden::PIX_TYPE Image_series::get_pixel_type () const virtual
Returns the size of the image pixels.
Implements iden::Image_base.
References iden::ERROR, image_, iden::U16, and iden::U8.
utilities::Tuple< unsigned int, 2 > Image_series::get_plane_dims () const virtual
Returns the plane dimensions.
Implements iden::Image_base.
References image_.
Md_store * Image_series::get_plane_md (const MD_parser & parser) const virtual
Returns the current plane's meta data.
Returns a pointer that needs to be cleaned up.
Implements iden::Image_base.
References image_, and iden::MD_parser::parse_md().
Referenced by main().
const void * Image_series::get_plane_pixels () const virtual
Returns the data of the current plane.
This pointer is managed internally and should not be deleted. This pointer is only good until the object is closed or until the plane is changed, which ever comes first. To determine how to cast this pointer call get_pixel_type.
Implements iden::Image_base.
References image_.
WORD Image_series::get_scan_step () const virtual
returns the plane scan_step
Implements iden::Image_base.
References image_.
bool Image_series::init (const std::string & base_name)
References basename_, dirname_, padding_, planecount_, select_plane(), selector(), and selector_name.
Referenced by main().
void Image_series::select_plane (unsigned int plane) virtual
Set the plane w.
Implements iden::Image_base.
References basename_, cur_plane_, dirname_, iden::F32, iden::format_name(), image_, padding_, pix_type_, planecount_, iden::S16, to_grey(), iden::U16, and iden::U8.
Referenced by init(), and main().
bool Image_series::to_grey () private
Converts the image to 8 bit grey scale.
References image_.
Referenced by select_plane().
Member Data Documentation
std::string iden::Image_series::basename_ private
Referenced by init(), and select_plane().
unsigned int iden::Image_series::cur_plane_ private
Referenced by select_plane().
std::string iden::Image_series::dirname_ private
Referenced by init(), and select_plane().
fipImage iden::Image_series::image_ private
Referenced by get_pixel_type(), get_plane_dims(), get_plane_md(), get_plane_pixels(), get_scan_step(), select_plane(), to_grey(), and ~Image_series().
bool iden::Image_series::image_open_ private
unsigned int iden::Image_series::padding_ private
Referenced by init(), and select_plane().
PIX_TYPE iden::Image_series::pix_type_ private
Referenced by select_plane().
unsigned int iden::Image_series::planecount_ private
Referenced by get_frame_count(), init(), and select_plane().
The documentation for this class was generated from the following files:
iden/include/image_series.h
iden/cxx/image_series.cpp