Particle Identification and Tracking: tracking::TA_disp Class Reference
tracking::TA_disp Class Reference
Track accumulator that computes the distribution of and for displacements.
#include <ta_disp.h>
Public Member Functions
void add_disp (const utilities::Tuplef &displacement, unsigned steps)
Add a track segment displacement.
unsigned max_step () const
Returns the maximum step that the accumulator can deal with.
TA_disp (unsigned max_steps, unsigned r_nbins, float max_r, unsigned t_nbins)
Constructor.
~TA_disp ()
Destructor.
void output_to_wrapper (utilities::Generic_wrapper &out, const utilities::Md_store &md_store) const
Output function.
Private Attributes
std::vector< utilities::Histogram > r_disp_
vector of Histogram objects, one for each time step, for squared displacement.
std::vector< utilities::Histogram > theta_
A vector of histograms for.
unsigned max_step_
Maximum time step.
Detailed Description
Track accumulator that computes the distribution of and for displacements.
Constructor & Destructor Documentation
TA_disp::TA_disp (unsigned max_steps, unsigned r_nbins, float max_r, unsigned t_nbins)
Constructor.
TA_disp::~TA_disp ()
Destructor.
Member Function Documentation
void TA_disp::add_disp (const utilities::Tuplef & displacement, unsigned steps) virtual
Add a track segment displacement.
Parameters
[in] displacement The net displacement of the track segment.
[in] steps The number of time steps in the track segment.
Implements tracking::Trk_accumulator.
References max_step_, r_disp_, and theta_.
unsigned tracking::TA_disp::max_step () const inline virtual
Returns the maximum step that the accumulator can deal with.
Implements tracking::Trk_accumulator.
References max_step_.
void TA_disp::output_to_wrapper (utilities::Generic_wrapper & out, const utilities::Md_store & md_store) const
Output function.
References utilities::Generic_wrapper::add_meta_data(), base_name, utilities::Generic_wrapper::close_group(), utilities::Generic_wrapper::close_wrapper(), utilities::format_name(), utilities::Md_store::get_value(), utilities::Generic_wrapper::is_open(), max_step_, utilities::Generic_wrapper::open_group(), utilities::Generic_wrapper::open_wrapper(), r_disp_, and theta_.
Member Data Documentation
unsigned tracking::TA_disp::max_step_ private
Maximum time step.
Referenced by add_disp(), max_step(), and output_to_wrapper().
std::vector<utilities::Histogram> tracking::TA_disp::r_disp_ private
vector of Histogram objects, one for each time step, for squared displacement.
Referenced by add_disp(), and output_to_wrapper().
std::vector<utilities::Histogram> tracking::TA_disp::theta_ private
A vector of histograms for.
Referenced by add_disp(), and output_to_wrapper().
The documentation for this class was generated from the following files:
common_src/include/ta_disp.h
common_src/cxx/ta_disp.cpp