Particle Identification and Tracking: tracking::Accum_chi4_self Class Reference
tracking::Accum_chi4_self Class Reference
Computes the self part of the susceptibility.
#include <accum_chi4_self.h>
Public Member Functions
void add_particle (const particle *)
Adds a particle.
void out_to_wrapper (utilities::Generic_wrapper &, const utilities::Md_store &md_store) const
outputs the result of the computation to the wrapper
Accum_chi4_self (unsigned max_t, float min_l, float max_l, unsigned int l_steps, float(*w)(float, float))
Constructor.
~Accum_chi4_self ()
void add_to_chi4 (std::vector< float > &Q_accum, std::vector< float > &Q2_accum, const int time_steps) const
Add the results of a single plane to compute average over t.
Private Member Functions
unsigned int to_indx (unsigned int a, unsigned int b)
internal hash function to deal with cord -> index
Private Attributes
unsigned int max_step_
maximum t step
unsigned int l_steps_
number of l values to try
float l_step_sz_
l step size
float l_min_
l step size
float(* w_)(float, float)
w function.
std::vector< float > Q_
Data vector.
std::vector< unsigned int > count_
Data vector.
Detailed Description
Computes the self part of the susceptibility.
Constructor & Destructor Documentation
Accum_chi4_self::Accum_chi4_self (unsigned max_t, float min_l, float max_l, unsigned int l_steps, float(*)(float, float) w)
Constructor.
Accum_chi4_self::~Accum_chi4_self ()
Member Function Documentation
void Accum_chi4_self::add_particle (const particle *) virtual
Adds a particle.
The sub class determines what is computed from the particle.
Implements tracking::Accumulator.
References count_, tracking::particle_track::distancesq_corrected(), tracking::particle_track::get_next(), l_min_, l_step_sz_, l_steps_, max_step_, Q_, to_indx(), and w_.
void Accum_chi4_self::add_to_chi4 (std::vector< float > & Q_accum, std::vector< float > & Q2_accum, const int time_steps) const
Add the results of a single plane to compute average over t.
References count_, l_steps_, and Q_.
void Accum_chi4_self::out_to_wrapper (utilities::Generic_wrapper & , const utilities::Md_store & md_store) const virtual
outputs the result of the computation to the wrapper
Implements tracking::Accumulator.
References utilities::Generic_wrapper::add_dset(), base_name, utilities::Generic_wrapper::close_wrapper(), utilities::Md_store::contains_key(), count_, utilities::format_name(), utilities::Md_store::get_value(), utilities::Generic_wrapper::is_open(), l_steps_, max_step_, utilities::Generic_wrapper::open_group(), utilities::Generic_wrapper::open_wrapper(), Q_, utilities::V_FLOAT, and utilities::V_UINT.
unsigned int tracking::Accum_chi4_self::to_indx (unsigned int a, unsigned int b) inline private
internal hash function to deal with cord -> index
References l_steps_.
Referenced by add_particle().
Member Data Documentation
std::vector<unsigned int> tracking::Accum_chi4_self::count_ private
Data vector.
Referenced by add_particle(), add_to_chi4(), and out_to_wrapper().
float tracking::Accum_chi4_self::l_min_ private
l step size
Referenced by add_particle().
float tracking::Accum_chi4_self::l_step_sz_ private
l step size
Referenced by add_particle().
unsigned int tracking::Accum_chi4_self::l_steps_ private
number of l values to try
Referenced by add_particle(), add_to_chi4(), out_to_wrapper(), and to_indx().
unsigned int tracking::Accum_chi4_self::max_step_ private
maximum t step
Referenced by add_particle(), and out_to_wrapper().
std::vector<float> tracking::Accum_chi4_self::Q_ private
Data vector.
Referenced by add_particle(), add_to_chi4(), and out_to_wrapper().
float(* tracking::Accum_chi4_self::w_)(float, float) private
w function.
See: J. Chem. Phys., Vol. 119, No. 14, 8 October 2003
A.R. Abate and D.J. Durian. (2007). Topological persistence and dynamical heterogeneities near jamming. Physical Review E 76, 021306.
PRL 95, 265701 (2005)
260 nature physics VOL 3 APRIL 2007 www.nature.com/naturephysics
Referenced by add_particle().
The documentation for this class was generated from the following files:
common_src/include/accum_chi4_self.h
common_src/cxx/accum_chi4_self.cpp