Particle Identification and Tracking: utilities::Wrapper_i_dummy Class Reference
utilities::Wrapper_i_dummy Class Reference
Wrapper class for testing purposes.
#include <wrapper_i_dummy.h>
Public Member Functions
int get_value (int &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
float get_value (float &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::complex< float > get_value (std::complex< float > &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::set< D_TYPE > get_data_types () const
Returns a set of the data types.
int get_num_entries (unsigned int frame) const
Return the number of entries the specified frame.
int get_num_entries () const
Return the total number of entries in the wrapper.
int get_num_frames () const
Return the number of frames.
bool contains_type (D_TYPE in) const
Returns if the wrapper contains the specified data type.
Tuplef get_dims () const
Returns the dimension of each 'frame' of the data in the wrapper.
~Wrapper_i_dummy ()
Wrapper_i_dummy (const std::set< utilities::D_TYPE > &d_types, int count, int frames)
int get_value (int &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
float get_value (float &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::complex< float > get_value (std::complex< float > &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::set< D_TYPE > get_data_types () const
Returns a set of the data types.
int get_num_entries (unsigned int frame) const
Return the number of entries the specified frame.
int get_num_entries () const
Return the total number of entries in the wrapper.
int get_num_frames () const
Return the number of frames.
bool contains_type (D_TYPE in) const
Returns if the wrapper contains the specified data type.
Tuplef get_dims () const
Returns the dimension of each 'frame' of the data in the wrapper.
~Wrapper_i_dummy ()
Wrapper_i_dummy (const std::set< utilities::D_TYPE > &d_types, int count, int frames)
int get_value (int &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
float get_value (float &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::complex< float > get_value (std::complex< float > &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::set< D_TYPE > get_data_types () const
Returns a set of the data types.
int get_num_entries (unsigned int frame) const
Return the number of entries the specified frame.
int get_num_entries () const
Return the total number of entries in the wrapper.
int get_num_frames () const
Return the number of frames.
bool contains_type (D_TYPE in) const
Returns if the wrapper contains the specified data type.
Tuplef get_dims () const
Returns the dimension of each 'frame' of the data in the wrapper.
~Wrapper_i_dummy ()
Wrapper_i_dummy (const std::set< utilities::D_TYPE > &d_types, int count, int frames)
int get_value (int &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
float get_value (float &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::complex< float > get_value (std::complex< float > &out, int ind, D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::set< D_TYPE > get_data_types () const
Returns a set of the data types.
int get_num_entries (unsigned int frame) const
Return the number of entries the specified frame.
int get_num_entries () const
Return the total number of entries in the wrapper.
int get_num_frames () const
Return the number of frames.
bool contains_type (D_TYPE in) const
Returns if the wrapper contains the specified data type.
Tuplef get_dims () const
Returns the dimension of each 'frame' of the data in the wrapper.
~Wrapper_i_dummy ()
Wrapper_i_dummy (const std::set< utilities::D_TYPE > &d_types, int count, int frames)
Meta data handling functions
const Md_store * get_Md_store (unsigned int j) const
Returns a pointer to plane j's meta data store.
Md_store * get_Md_store (unsigned int j)
Returns a pointer to plane j's meta data store.
void set_Md_store (unsigned int j, Md_store *in)
Sets the Md_store for plane j.
void set_Md_store_size (unsigned int j)
Sets the size of the md_stores_ vector.
unsigned int get_Md_store_size ()
Gets the size of the md_stores_ vector.
void clear_Md_store (unsigned int j)
Deletes plane j's Md_store.
Private Attributes
std::set< D_TYPE > d_types_
int frames_
int count_
int counter_
Static Private Attributes
static const int x_max_ = 10
static const int y_max_ = 10
Detailed Description
Wrapper class for testing purposes.
Constructor & Destructor Documentation
utilities::Wrapper_i_dummy::~Wrapper_i_dummy () inline
utilities::Wrapper_i_dummy::Wrapper_i_dummy (const std::set< utilities::D_TYPE > & d_types, int count, int frames) inline
utilities::Wrapper_i_dummy::~Wrapper_i_dummy () inline
utilities::Wrapper_i_dummy::Wrapper_i_dummy (const std::set< utilities::D_TYPE > & d_types, int count, int frames) inline
utilities::Wrapper_i_dummy::~Wrapper_i_dummy () inline
utilities::Wrapper_i_dummy::Wrapper_i_dummy (const std::set< utilities::D_TYPE > & d_types, int count, int frames) inline
utilities::Wrapper_i_dummy::~Wrapper_i_dummy () inline
utilities::Wrapper_i_dummy::Wrapper_i_dummy (const std::set< utilities::D_TYPE > & d_types, int count, int frames) inline
Member Function Documentation
void Wrapper_in::clear_Md_store (unsigned int j) inherited
Deletes plane j's Md_store.
References utilities::Wrapper_in::md_stores_.
bool utilities::Wrapper_i_dummy::contains_type (D_TYPE type) const inline virtual
Returns if the wrapper contains the specified data type.
Implements utilities::Wrapper_in.
References d_types_.
bool utilities::Wrapper_i_dummy::contains_type (D_TYPE type) const inline virtual
Returns if the wrapper contains the specified data type.
Implements utilities::Wrapper_in.
References d_types_.
bool utilities::Wrapper_i_dummy::contains_type (D_TYPE type) const inline virtual
Returns if the wrapper contains the specified data type.
Implements utilities::Wrapper_in.
References d_types_.
bool utilities::Wrapper_i_dummy::contains_type (D_TYPE type) const inline virtual
Returns if the wrapper contains the specified data type.
Implements utilities::Wrapper_in.
References d_types_.
std::set<D_TYPE> utilities::Wrapper_i_dummy::get_data_types () const inline virtual
Returns a set of the data types.
Use the other version
Implements utilities::Wrapper_in.
References d_types_.
std::set<D_TYPE> utilities::Wrapper_i_dummy::get_data_types () const inline virtual
Returns a set of the data types.
Use the other version
Implements utilities::Wrapper_in.
References d_types_.
std::set<D_TYPE> utilities::Wrapper_i_dummy::get_data_types () const inline virtual
Returns a set of the data types.
Use the other version
Implements utilities::Wrapper_in.
References d_types_.
std::set<D_TYPE> utilities::Wrapper_i_dummy::get_data_types () const inline virtual
Returns a set of the data types.
Use the other version
Implements utilities::Wrapper_in.
References d_types_.
Tuplef utilities::Wrapper_i_dummy::get_dims () const inline virtual
Returns the dimension of each 'frame' of the data in the wrapper.
Implements utilities::Wrapper_in.
Tuplef utilities::Wrapper_i_dummy::get_dims () const inline virtual
Returns the dimension of each 'frame' of the data in the wrapper.
Implements utilities::Wrapper_in.
Tuplef utilities::Wrapper_i_dummy::get_dims () const inline virtual
Returns the dimension of each 'frame' of the data in the wrapper.
Implements utilities::Wrapper_in.
Tuplef utilities::Wrapper_i_dummy::get_dims () const inline virtual
Returns the dimension of each 'frame' of the data in the wrapper.
Implements utilities::Wrapper_in.
const Md_store * Wrapper_in::get_Md_store (unsigned int j) const inherited
Returns a pointer to plane j's meta data store.
Const version
References utilities::Wrapper_in::md_stores_.
Referenced by tracking::Master_box::get_Md_store(), and tracking::hash_case::init().
Md_store * Wrapper_in::get_Md_store (unsigned int j) inherited
Returns a pointer to plane j's meta data store.
Const version
References utilities::Wrapper_in::md_stores_.
unsigned int Wrapper_in::get_Md_store_size () inherited
Gets the size of the md_stores_ vector.
References utilities::Wrapper_in::md_stores_.
int utilities::Wrapper_i_dummy::get_num_entries (unsigned int frame) const inline virtual
Return the number of entries the specified frame.
Implements utilities::Wrapper_in.
References count_.
int utilities::Wrapper_i_dummy::get_num_entries () const inline virtual
Return the total number of entries in the wrapper.
Implements utilities::Wrapper_in.
References count_, and frames_.
int utilities::Wrapper_i_dummy::get_num_entries (unsigned int frame) const inline virtual
Return the number of entries the specified frame.
Implements utilities::Wrapper_in.
References count_.
int utilities::Wrapper_i_dummy::get_num_entries () const inline virtual
Return the total number of entries in the wrapper.
Implements utilities::Wrapper_in.
References count_, and frames_.
int utilities::Wrapper_i_dummy::get_num_entries (unsigned int frame) const inline virtual
Return the number of entries the specified frame.
Implements utilities::Wrapper_in.
References count_.
int utilities::Wrapper_i_dummy::get_num_entries () const inline virtual
Return the total number of entries in the wrapper.
Implements utilities::Wrapper_in.
References count_, and frames_.
int utilities::Wrapper_i_dummy::get_num_entries (unsigned int frame) const inline virtual
Return the number of entries the specified frame.
Implements utilities::Wrapper_in.
References count_.
int utilities::Wrapper_i_dummy::get_num_entries () const inline virtual
Return the total number of entries in the wrapper.
Implements utilities::Wrapper_in.
References count_, and frames_.
int utilities::Wrapper_i_dummy::get_num_frames () const inline virtual
Return the number of frames.
Implements utilities::Wrapper_in.
References frames_.
int utilities::Wrapper_i_dummy::get_num_frames () const inline virtual
Return the number of frames.
Implements utilities::Wrapper_in.
References frames_.
int utilities::Wrapper_i_dummy::get_num_frames () const inline virtual
Return the number of frames.
Implements utilities::Wrapper_in.
References frames_.
int utilities::Wrapper_i_dummy::get_num_frames () const inline virtual
Return the number of frames.
Implements utilities::Wrapper_in.
References frames_.
int utilities::Wrapper_i_dummy::get_value (int & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
References counter_, and utilities::D_FRAME.
int utilities::Wrapper_i_dummy::get_value (int & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
References counter_, and utilities::D_FRAME.
float utilities::Wrapper_i_dummy::get_value (float & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
References utilities::D_XPOS, utilities::D_YPOS, and x_max_.
float utilities::Wrapper_i_dummy::get_value (float & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
References utilities::D_XPOS, utilities::D_YPOS, and x_max_.
int utilities::Wrapper_i_dummy::get_value (int & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
References counter_, and utilities::D_FRAME.
std::complex<float> utilities::Wrapper_i_dummy::get_value (std::complex< float > & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
std::complex<float> utilities::Wrapper_i_dummy::get_value (std::complex< float > & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
float utilities::Wrapper_i_dummy::get_value (float & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
int utilities::Wrapper_i_dummy::get_value (int & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
References counter_, and utilities::D_FRAME.
std::complex<float> utilities::Wrapper_i_dummy::get_value (std::complex< float > & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
float utilities::Wrapper_i_dummy::get_value (float & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
std::complex<float> utilities::Wrapper_i_dummy::get_value (std::complex< float > & out, int ind, D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
void Wrapper_in::set_Md_store (unsigned int j, Md_store * in) inherited
Sets the Md_store for plane j.
When the pointer is assigned the wrapper takes ownership of the pointer and will clean it up.
References utilities::Wrapper_in::md_stores_.
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), main(), utilities::Wrapper_i_hdf::priv_init(), and iden::Iden::process_frame().
void Wrapper_in::set_Md_store_size (unsigned int j) inherited
Sets the size of the md_stores_ vector.
References utilities::Wrapper_in::md_stores_.
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), main(), utilities::Wrapper_i_hdf::priv_init(), and iden::Wrapper_i_plu::Wrapper_i_plu().
Member Data Documentation
int utilities::Wrapper_i_dummy::count_ private
Referenced by get_num_entries().
int utilities::Wrapper_i_dummy::counter_ mutable private
Referenced by get_value().
std::set< D_TYPE > utilities::Wrapper_i_dummy::d_types_ private
Referenced by contains_type(), and get_data_types().
int utilities::Wrapper_i_dummy::frames_ private
Referenced by get_num_entries(), and get_num_frames().
static const int utilities::Wrapper_i_dummy::x_max_ = 10 static private
Referenced by get_value().
static const int utilities::Wrapper_i_dummy::y_max_ = 10 static private
The documentation for this class was generated from the following files:
common_src/include/wrapper_i_dummy.h
testing/make_fake_hdf.cpp
testing/sofq_ND_test.cpp
testing/sofq_test.cpp