Particle Identification and Tracking: iden::Wrapper_i_plu Class Reference
iden::Wrapper_i_plu Class Reference
Wrapper class for dealing with data from Peter Lu's code.
#include <wrapper_i_plu.h>
Public Member Functions
void add_frame_data (Ipp32f[][9], int frame, int num)
adds a pointer to data_
int get_num_entries (unsigned int j) const
Return the number of entries the specified frame.
int get_num_entries () const
Return the total number of entries in the wrapper.
void print () const
int get_value (int &out, int ind, utilities::D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
float get_value (float &out, int ind, utilities::D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
std::complex< float > get_value (std::complex< float > &out, int ind, utilities::D_TYPE type, int frame) const
Returns the value of the type specified from the particle selected.
void set_dims (const utilities::Tuple< float, 2 > &)
Wrapper_i_plu (int, utilities::Tuple< float, 2 >)
Wrapper_i_plu (int)
virtual ~Wrapper_i_plu ()
bool contains_type (utilities::D_TYPE) const
Returns if the wrapper contains the specified data type.
int get_num_frames () const
Return the number of frames.
std::set< utilities::D_TYPE > get_data_types () const
Returns a set of the data types.
utilities::Tuple< float, 2 > get_dims () const
Returns the dimension of each 'frame' of the data in the wrapper.
Meta data handling functions
const Md_store * get_Md_store (unsigned int j) const
Returns a pointer to plane j's meta data store.
Md_store * get_Md_store (unsigned int j)
Returns a pointer to plane j's meta data store.
void set_Md_store (unsigned int j, Md_store *in)
Sets the Md_store for plane j.
void set_Md_store_size (unsigned int j)
Sets the size of the md_stores_ vector.
unsigned int get_Md_store_size ()
Gets the size of the md_stores_ vector.
void clear_Md_store (unsigned int j)
Deletes plane j's Md_store.
Protected Attributes
std::set< utilities::D_TYPE > data_types_
A map between the data types and a posistion in the data structure.
utilities::Data_map data_map_
object for fast lookup
int count_
count of particles added
utilities::Tuple< float, 2 > dims_
dimensions of the images being shoved in
Private Attributes
std::vector< Ipp32f(*)[9]> data_
vectors of pointers to data The wrapper owns these pointers
std::vector< int > frame_count_
Static Private Attributes
static const int cols = 9
Detailed Description
Wrapper class for dealing with data from Peter Lu's code.
Constructor & Destructor Documentation
iden::Wrapper_i_plu::Wrapper_i_plu (int , utilities::Tuple< float, 2 >)
Wrapper_i_plu::Wrapper_i_plu (int frames)
References utilities::D_DX, utilities::D_DY, utilities::D_E, utilities::D_FRAME, utilities::D_I, utilities::D_MULT, utilities::D_R2, utilities::D_XPOS, utilities::D_YPOS, data_map_, data_types_, utilities::Data_map::set_lookup(), and utilities::Wrapper_in::set_Md_store_size().
Wrapper_i_plu::~Wrapper_i_plu () virtual
References data_.
Member Function Documentation
void Wrapper_i_plu::add_frame_data (Ipp32f data[][9], int frame, int num)
adds a pointer to data_
References count_, data_, and frame_count_.
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), and iden::Iden::process_frame().
void Wrapper_in::clear_Md_store (unsigned int j) inherited
Deletes plane j's Md_store.
References utilities::Wrapper_in::md_stores_.
bool Wrapper_i_plu::contains_type (utilities::D_TYPE type) const virtual
Returns if the wrapper contains the specified data type.
Implements utilities::Wrapper_in.
References data_types_.
std::set<utilities::D_TYPE> iden::Wrapper_i_plu::get_data_types () const inline virtual
Returns a set of the data types.
Use the other version
Implements utilities::Wrapper_in.
References data_types_.
Referenced by main().
Tuple< float, 2 > Wrapper_i_plu::get_dims () const virtual
Returns the dimension of each 'frame' of the data in the wrapper.
Implements utilities::Wrapper_in.
References dims_.
Referenced by main().
const Md_store * Wrapper_in::get_Md_store (unsigned int j) const inherited
Returns a pointer to plane j's meta data store.
Const version
References utilities::Wrapper_in::md_stores_.
Referenced by tracking::Master_box::get_Md_store(), and tracking::hash_case::init().
Md_store * Wrapper_in::get_Md_store (unsigned int j) inherited
Returns a pointer to plane j's meta data store.
Const version
References utilities::Wrapper_in::md_stores_.
unsigned int Wrapper_in::get_Md_store_size () inherited
Gets the size of the md_stores_ vector.
References utilities::Wrapper_in::md_stores_.
int Wrapper_i_plu::get_num_entries (unsigned int frame) const virtual
Return the number of entries the specified frame.
Implements utilities::Wrapper_in.
References frame_count_.
Referenced by main().
int Wrapper_i_plu::get_num_entries () const virtual
Return the total number of entries in the wrapper.
Implements utilities::Wrapper_in.
References count_.
int iden::Wrapper_i_plu::get_num_frames () const inline virtual
Return the number of frames.
Implements utilities::Wrapper_in.
References frame_count_.
Referenced by main().
int iden::Wrapper_i_plu::get_value (int & out, int ind, utilities::D_TYPE type, int frame) const virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
Referenced by iden::Iden::fill_wrapper_avg().
float iden::Wrapper_i_plu::get_value (float & out, int ind, utilities::D_TYPE type, int frame) const virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
std::complex<float> iden::Wrapper_i_plu::get_value (std::complex< float > & out, int ind, utilities::D_TYPE type, int frame) const inline virtual
Returns the value of the type specified from the particle selected.
Parameters
out [out] the value
ind [in] the index of the particle
type [in] the D_TYPE
frame [in] the frame the particle is in
Returns
the value
Implements utilities::Wrapper_in.
void Wrapper_i_plu::print () const
References count_, and data_.
void Wrapper_i_plu::set_dims (const utilities::Tuple< float, 2 > &)
References dims_.
void Wrapper_in::set_Md_store (unsigned int j, Md_store * in) inherited
Sets the Md_store for plane j.
When the pointer is assigned the wrapper takes ownership of the pointer and will clean it up.
References utilities::Wrapper_in::md_stores_.
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), main(), utilities::Wrapper_i_hdf::priv_init(), and iden::Iden::process_frame().
void Wrapper_in::set_Md_store_size (unsigned int j) inherited
Sets the size of the md_stores_ vector.
References utilities::Wrapper_in::md_stores_.
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), main(), utilities::Wrapper_i_hdf::priv_init(), and Wrapper_i_plu().
Member Data Documentation
const int iden::Wrapper_i_plu::cols = 9 static private
int iden::Wrapper_i_plu::count_ protected
count of particles added
Referenced by add_frame_data(), get_num_entries(), and print().
std::vector<Ipp32f(*) [9]> iden::Wrapper_i_plu::data_ private
vectors of pointers to data The wrapper owns these pointers
Referenced by add_frame_data(), print(), and ~Wrapper_i_plu().
utilities::Data_map iden::Wrapper_i_plu::data_map_ protected
object for fast lookup
Referenced by Wrapper_i_plu().
std::set<utilities::D_TYPE> iden::Wrapper_i_plu::data_types_ protected
A map between the data types and a posistion in the data structure.
This orginally had been burried down in the derived classes, but I couldn't think of a data structure for storing particle data where this sort of thing wasn't uesful. Thus, it has been dragged up to the top level.
Referenced by contains_type(), get_data_types(), and Wrapper_i_plu().
utilities::Tuple<float,2> iden::Wrapper_i_plu::dims_ protected
dimensions of the images being shoved in
Referenced by get_dims(), and set_dims().
std::vector<int> iden::Wrapper_i_plu::frame_count_ private
Referenced by add_frame_data(), get_num_entries(), and get_num_frames().
The documentation for this class was generated from the following files:
iden/include/wrapper_i_plu.h
iden/cxx/wrapper_i_plu.cpp