Particle Identification and Tracking: iden::Image_stack Class Reference
iden::Image_stack Class Reference
#include <image_stack.h>
Public Member Functions
Image_stack (std::string fname)
~Image_stack ()
void select_plane (unsigned int plane)
Set the plane w.
const void * get_plane_pixels () const
Returns the data of the current plane.
utilities::Md_store * get_plane_md (const MD_parser &parser) const
Returns the current plane's meta data.
utilities::Tuple< unsigned int, 2 > get_plane_dims () const
Returns the plane dimensions.
WORD get_scan_step () const
returns the plane scan_step
int get_frame_count () const
Returns the number of planes in the image.
PIX_TYPE get_pixel_type () const
Returns the size of the image pixels.
void initialize ()
Initialization function.
void deinitialize ()
Cleans up the file, but does not take the FreeImage down.
Private Member Functions
bool to_grey ()
Converts the image to 8 bit grey scale.
Private Attributes
std::string fname_
unsigned int cur_plane_
bool stack_open_
fipMultiPage src_
fipImage image_
bool convert_to_grey_
PIX_TYPE pix_type_
Constructor & Destructor Documentation
Image_stack::Image_stack (std::string fname)
Image_stack::~Image_stack ()
References deinitialize().
Member Function Documentation
void Image_stack::deinitialize ()
Cleans up the file, but does not take the FreeImage down.
References src_.
Referenced by ~Image_stack().
int Image_stack::get_frame_count () const virtual
Returns the number of planes in the image.
Implements iden::Image_base.
References src_.
Referenced by main().
PIX_TYPE Image_stack::get_pixel_type () const virtual
Returns the size of the image pixels.
Implements iden::Image_base.
References pix_type_.
utilities::Tuple< unsigned int, 2 > Image_stack::get_plane_dims () const virtual
Returns the plane dimensions.
Implements iden::Image_base.
References image_.
Md_store * Image_stack::get_plane_md (const MD_parser & parser) const virtual
Returns the current plane's meta data.
Returns a pointer that needs to be cleaned up.
Implements iden::Image_base.
References image_, and iden::MD_parser::parse_md().
Referenced by main().
const void * Image_stack::get_plane_pixels () const virtual
Returns the data of the current plane.
This pointer is managed internally and should not be deleted. This pointer is only good until the object is closed or until the plane is changed, which ever comes first. To determine how to cast this pointer call get_pixel_type.
Implements iden::Image_base.
References image_.
WORD Image_stack::get_scan_step () const virtual
returns the plane scan_step
Implements iden::Image_base.
References image_.
void Image_stack::initialize ()
Initialization function.
Opens up the file and checks the data type
References convert_to_grey_, cur_plane_, iden::F32, fname_, image_, pix_type_, iden::S16, src_, to_grey(), iden::U16, and iden::U8.
Referenced by main().
void Image_stack::select_plane (unsigned int plane) virtual
Set the plane w.
Implements iden::Image_base.
References convert_to_grey_, cur_plane_, image_, src_, and to_grey().
Referenced by main().
bool Image_stack::to_grey () private
Converts the image to 8 bit grey scale.
References image_.
Referenced by initialize(), and select_plane().
Member Data Documentation
bool iden::Image_stack::convert_to_grey_ private
Referenced by initialize(), and select_plane().
unsigned int iden::Image_stack::cur_plane_ private
Referenced by initialize(), and select_plane().
std::string iden::Image_stack::fname_ private
Referenced by initialize().
fipImage iden::Image_stack::image_ private
Referenced by get_plane_dims(), get_plane_md(), get_plane_pixels(), get_scan_step(), initialize(), select_plane(), and to_grey().
PIX_TYPE iden::Image_stack::pix_type_ private
Referenced by get_pixel_type(), and initialize().
fipMultiPage iden::Image_stack::src_ private
Referenced by deinitialize(), get_frame_count(), initialize(), and select_plane().
bool iden::Image_stack::stack_open_ private
The documentation for this class was generated from the following files:
iden/include/image_stack.h
iden/cxx/image_stack.cpp