Particle Identification and Tracking: tracking::Master_box Class Reference
tracking::Master_box Class Reference
Class to hold the master list of all particles to be processed by the code.
#include <master_box_t.h>
Public Member Functions
void print ()
prints out a representation of this in some useful way
void push (particle *next)
add next particle
particle * get_particle (int n)
return a pointer to particle in the location
void append_to_data_types (utilities::D_TYPE type)
adds a new type to the data_types
Master_box ()
Constructor.
unsigned int size ()
Returns the total number of particles contained in the Master_box.
void clean_pos_link ()
Cleans up hanging lists from the tracking procedure.
void init (const utilities::Wrapper_in &w_in, utilities::Filter &filt)
initialization to take in a wrapper
void compute_accum (tracking::Accumulator &in) const
Puts all of the particles in to the Accumulator.
const utilities::Md_store * get_Md_store (unsigned int j) const
Returns a pointer to the Md_store for plane j in the input wrapper.
~Master_box ()
Destructor.
Protected Member Functions
void priv_init (utilities::Filter const *const filt)
private initialization function
Protected Attributes
std::vector< particle * > particle_vec_
Vector that contains pointers to all of the particles that are going to be considered in the code.
const utilities::Wrapper_in * in_wrapper_
Pointer to wrapper to take care of particle location input data.
unsigned int imagesz1
unsigned int imagesz2
std::set< utilities::D_TYPE > data_types
A set of the data types known by particles in the Master_box.
bool own_wrapper_
if the master box owns, and hence needs to delete the wrapper
Detailed Description
Class to hold the master list of all particles to be processed by the code.
Constructor & Destructor Documentation
Master_box::Master_box ()
Constructor.
Master_box::~Master_box ()
Destructor.
References tracking::particle_base::clear_wrapper_in(), in_wrapper_, own_wrapper_, and particle_vec_.
Member Function Documentation
void tracking::Master_box::append_to_data_types (utilities::D_TYPE type) inline
adds a new type to the data_types
References data_types.
void tracking::Master_box::clean_pos_link ()
Cleans up hanging lists from the tracking procedure.
void Master_box::compute_accum (tracking::Accumulator & in) const
Puts all of the particles in to the Accumulator.
References tracking::Accumulator::add_particle(), and particle_vec_.
Referenced by main().
const Md_store * Master_box::get_Md_store (unsigned int j) const
Returns a pointer to the Md_store for plane j in the input wrapper.
References utilities::Wrapper_in::get_Md_store(), and in_wrapper_.
Referenced by tracking::hash_case::init().
particle* tracking::Master_box::get_particle (int n) inline
return a pointer to particle in the location
References particle_vec_.
Referenced by tracking::hash_case::init(), tracking::Track_shelf::init(), and main().
void Master_box::init (const utilities::Wrapper_in & w_in, utilities::Filter & filt)
initialization to take in a wrapper
References in_wrapper_, own_wrapper_, priv_init(), and utilities::Filter::set_wrapper().
Referenced by main().
void Master_box::print ()
prints out a representation of this in some useful way
References particle_vec_.
void Master_box::priv_init (utilities::Filter const *const filt) protected
private initialization function
References data_types, utilities::Wrapper_in::get_data_types(), utilities::Wrapper_in::get_num_entries(), utilities::Wrapper_in::get_num_frames(), in_wrapper_, tracking::particle_base::intialize_wrapper_in(), and particle_vec_.
Referenced by init().
void tracking::Master_box::push (particle * next) inline
add next particle
References particle_vec_.
unsigned int tracking::Master_box::size () inline
Returns the total number of particles contained in the Master_box.
References particle_vec_.
Referenced by tracking::hash_case::init(), tracking::Track_shelf::init(), and main().
Member Data Documentation
std::set<utilities::D_TYPE> tracking::Master_box::data_types protected
A set of the data types known by particles in the Master_box.
Referenced by append_to_data_types(), and priv_init().
unsigned int tracking::Master_box::imagesz1 protected
Todo:
sort out this member
unsigned int tracking::Master_box::imagesz2 protected
Todo:
sort out this member
const utilities::Wrapper_in* tracking::Master_box::in_wrapper_ protected
Pointer to wrapper to take care of particle location input data.
This class is responcible for creating and destroying this wrapper. This pointer will be handed to every particle that is part of this Master_box. The exact type of wrapper that is made will be determined by the parameter object.
Referenced by get_Md_store(), init(), priv_init(), and ~Master_box().
bool tracking::Master_box::own_wrapper_ protected
if the master box owns, and hence needs to delete the wrapper
Referenced by init(), and ~Master_box().
std::vector<particle*> tracking::Master_box::particle_vec_ protected
Vector that contains pointers to all of the particles that are going to be considered in the code.
This class is responcible for making all of the objects to represent the particles. This is all done with pointers, not with objects to take anvatage of polymorphism. This class is responcible to creating and destroying all of the particle objects.
Referenced by compute_accum(), get_particle(), print(), priv_init(), push(), size(), and ~Master_box().
The documentation for this class was generated from the following files:
common_src/include/master_box_t.h
common_src/cxx/master_box_t.cpp