Particle Identification and Tracking: utilities::Wrapper_out Class Reference
utilities::Wrapper_out Class Reference abstract
ABC for output wrappers.
#include <wrapper_o.h>
Public Member Functions
virtual void add_meta_store (const Md_store *md_in)=0
Adds all the meta data in a Md_store object.
Output interface
New API for output wrappers, which is a bit more carefully thought about.
All derived classes must implement these and only these public functions (because of the way that pointers to this base class are used in the code, only these functions are available in the bulk of the code)
Typical life cycle:
-initialize wrapper -loop over frames (if wrapper knows about frames) –loop over particles —open particle —set values —close particle –close particles -close frames -finalize wrapper
virtual void initialize_wrapper ()=0
preforms any initialization that needs to be done the logic for this is to not needlessly open and close files, or creat matlab arrays if they arn't going to be used.
virtual void open_group (int group=0, int p_count=0, int wrapper_size=-1)=0
Opens a group to put particles into.
virtual void set_all_values (const tracking::particle *)=0
sets all of the values that the wrapper knows about by asking the particle
virtual void set_all_values (const tracking::Track_box *, const utilities::Tuple< float, 3 > &)=0
sets all of the values that the wrapper knows about by asking the particle.
virtual void close_group ()=0
Closes the currently open group.
virtual void finalize_wrapper ()=0
Performs any clean up.
virtual const std::set< D_TYPE > & get_content_tpyes () const =0
Returns a set containing the D_TYPES that the wrapper can cope with.
virtual ~Wrapper_out ()
virtual destructor
Wrapper_out ()
empty constructor
Group level metadata
adds meta data to a group that is specific the current computation
virtual void add_meta_data (const std::string &key, float val)=0
Adds a float meta-data.
virtual void add_meta_data (const std::string &key, const Tuple< float, 3 > &val)=0
Adds a Triple meta-data.
virtual void add_meta_data (const std::string &key, const Tuple< float, 2 > &val)=0
Adds a Pair meta-data.
virtual void add_meta_data (const std::string &key, const std::string &val)=0
Adds a string meta-data.
virtual void add_meta_data (const std::string &key, int val)=0
Adds an integer meta-data.
virtual void add_meta_data_comp (const std::string &key, float val)=0
Adds a float meta-data.
virtual void add_meta_data_comp (const std::string &key, const Tuple< float, 3 > &val)=0
Adds a Triple meta-data.
virtual void add_meta_data_comp (const std::string &key, const Tuple< float, 2 > &val)=0
Adds a Pair meta-data.
virtual void add_meta_data_comp (const std::string &key, const std::string &val)=0
Adds a string meta-data.
virtual void add_meta_data_comp (const std::string &key, int val)=0
Adds an integer meta-data.
Root level
adds meta data to the root group
virtual void add_meta_data_root (const std::string &key, float val)=0
Adds a float meta-data.
virtual void add_meta_data_root (const std::string &key, const Tuple< float, 3 > &val)=0
Adds a Triple meta-data.
virtual void add_meta_data_root (const std::string &key, const Tuple< float, 2 > &val)=0
Adds a Pair meta-data.
virtual void add_meta_data_root (const std::string &key, const std::string &val)=0
Adds a string meta-data.
virtual void add_meta_data_root (const std::string &key, int val)=0
Adds an integer meta-data.
virtual void add_meta_data (const std::string &key, float val, D_TYPE dset_type)=0
Adds metadata for datasets.
virtual void add_meta_data (const std::string &key, const Tuple< float, 3 > &val, D_TYPE dset_type)=0
Adds a Triple meta-data for a data set.
virtual void add_meta_data (const std::string &key, const Tuple< float, 2 > &val, D_TYPE dset_type)=0
Adds a Pair meta-data for a data set.
virtual void add_meta_data (const std::string &key, const std::string &val, D_TYPE dset_type)=0
Adds a string meta-data for a data set.
virtual void add_meta_data (const std::string &key, int val, D_TYPE dset_type)=0
Adds an integer meta-data for a data set.
virtual void add_meta_data_list (const Read_config &, const std::set< D_TYPE > &)=0
Adds all parameters from the Read_config object to the data sets in the set.
Detailed Description
ABC for output wrappers.
Constructor & Destructor Documentation
virtual utilities::Wrapper_out::~Wrapper_out () inline virtual
virtual destructor
utilities::Wrapper_out::Wrapper_out () inline
empty constructor
Member Function Documentation
virtual void utilities::Wrapper_out::add_meta_data (const std::string & key, float val) pure virtual
Adds a float meta-data.
Implemented in utilities::Wrapper_o_hdf.
Referenced by tracking::Track_box::output_to_wrapper().
virtual void utilities::Wrapper_out::add_meta_data (const std::string & key, const Tuple< float, 3 > & val) pure virtual
Adds a Triple meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data (const std::string & key, const Tuple< float, 2 > & val) pure virtual
Adds a Pair meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data (const std::string & key, const std::string & val) pure virtual
Adds a string meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data (const std::string & key, int val) pure virtual
Adds an integer meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data (const std::string & key, float val, D_TYPE dset_type) pure virtual
Adds metadata for datasets.
Adds a float meta-data for a data set
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data (const std::string & key, const Tuple< float, 3 > & val, D_TYPE dset_type) pure virtual
Adds a Triple meta-data for a data set.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data (const std::string & key, const Tuple< float, 2 > & val, D_TYPE dset_type) pure virtual
Adds a Pair meta-data for a data set.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data (const std::string & key, const std::string & val, D_TYPE dset_type) pure virtual
Adds a string meta-data for a data set.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data (const std::string & key, int val, D_TYPE dset_type) pure virtual
Adds an integer meta-data for a data set.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data_comp (const std::string & key, float val) pure virtual
Adds a float meta-data.
Implemented in utilities::Wrapper_o_hdf.
Referenced by tracking::Hash_shelf::output_to_wrapper().
virtual void utilities::Wrapper_out::add_meta_data_comp (const std::string & key, const Tuple< float, 3 > & val) pure virtual
Adds a Triple meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data_comp (const std::string & key, const Tuple< float, 2 > & val) pure virtual
Adds a Pair meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data_comp (const std::string & key, const std::string & val) pure virtual
Adds a string meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data_comp (const std::string & key, int val) pure virtual
Adds an integer meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data_list (const Read_config & , const std::set< D_TYPE > &) pure virtual
Adds all parameters from the Read_config object to the data sets in the set.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data_root (const std::string & key, float val) pure virtual
Adds a float meta-data.
Implemented in utilities::Wrapper_o_hdf.
Referenced by tracking::Track_shelf::output_link_to_wrapper(), and tracking::hash_case::output_to_wrapper().
virtual void utilities::Wrapper_out::add_meta_data_root (const std::string & key, const Tuple< float, 3 > & val) pure virtual
Adds a Triple meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data_root (const std::string & key, const Tuple< float, 2 > & val) pure virtual
Adds a Pair meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data_root (const std::string & key, const std::string & val) pure virtual
Adds a string meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_data_root (const std::string & key, int val) pure virtual
Adds an integer meta-data.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::add_meta_store (const Md_store * md_in) pure virtual
Adds all the meta data in a Md_store object.
Implemented in utilities::Wrapper_o_hdf.
Referenced by tracking::Hash_shelf::output_to_wrapper().
virtual void utilities::Wrapper_out::close_group () pure virtual
Closes the currently open group.
Throws an error if there is no open group.
Implemented in utilities::Wrapper_o_hdf.
Referenced by tracking::Track_shelf::output_link_to_wrapper(), tracking::Track_box::output_to_wrapper(), and tracking::Hash_shelf::output_to_wrapper().
virtual void utilities::Wrapper_out::finalize_wrapper () pure virtual
Performs any clean up.
that needs to be done such as closing a file
Implemented in utilities::Wrapper_o_hdf, and utilities::wrapper_o_file.
virtual const std::set<D_TYPE>& utilities::Wrapper_out::get_content_tpyes () const pure virtual
Returns a set containing the D_TYPES that the wrapper can cope with.
Implemented in utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::initialize_wrapper () pure virtual
preforms any initialization that needs to be done the logic for this is to not needlessly open and close files, or creat matlab arrays if they arn't going to be used.
It also allows the wrapper object to be reused (ie, do all the processing, output one subset of data to one place, and another subset to another place
Implemented in utilities::wrapper_o_file, and utilities::Wrapper_o_hdf.
virtual void utilities::Wrapper_out::open_group (int group = 0, int p_count = 0, int wrapper_size = -1) pure virtual
Opens a group to put particles into.
Parameters
group the index of the group to be opened
p_count the number of particles to expect
wrapper_size the size of the group of the underlying wrapper, if <0, then set equal to p_count
Implemented in utilities::Wrapper_o_hdf.
Referenced by tracking::Track_shelf::output_link_to_wrapper(), tracking::Track_box::output_to_wrapper(), and tracking::Hash_shelf::output_to_wrapper().
virtual void utilities::Wrapper_out::set_all_values (const tracking::particle *) pure virtual
sets all of the values that the wrapper knows about by asking the particle
Implemented in utilities::Wrapper_o_hdf.
Referenced by tracking::Track_shelf::output_link_to_wrapper(), tracking::Track_box::output_to_wrapper(), and tracking::hash_box::output_to_wrapper().
virtual void utilities::Wrapper_out::set_all_values (const tracking::Track_box * , const utilities::Tuple< float, 3 > &) pure virtual
sets all of the values that the wrapper knows about by asking the particle.
This function is for outputting the results of 3D linking
Implemented in utilities::Wrapper_o_hdf.
The documentation for this class was generated from the following file:
common_src/include/wrapper_o.h