Particle Identification and Tracking: iden::Iden Class Reference
iden::Iden Class Reference
Class to encapsulate all of the image processing for particle identification.
#include <iden.h>
Public Member Functions
Iden (const utilities::Md_store &in)
~Iden ()
void set_image_src (Image_base *image)
void set_md_parser (MD_parser *parser)
void set_params (const utilities::Md_store &param_in)
Set the parameters used by this iden object to extract features.
Wrapper_i_plu * fill_wrapper (unsigned int frames=0, unsigned int start=0)
Wrapper_i_plu * fill_wrapper_avg (unsigned int frames=0, unsigned int start=0)
void process_frame (const Image2D &img_in, unsigned int frame_number, const utilities::Md_store *md_store_in, Wrapper_i_plu &wrapper_out) const
void process_frames (const Image_base &imgs, unsigned int start_frame, unsigned int frames, Wrapper_i_plu &wrapper_out) const
void process_frames_avg (const Image_base &imgs, unsigned int avg_count, unsigned int start_frame, unsigned int frames, Wrapper_i_plu &wrapper_out) const
Private Attributes
Image_base * img_src_
The source of the images to process.
MD_parser * parser_
Parser for metadata.
utilities::Md_store params_
Parameter object, holds the parameters for the image processing.
Detailed Description
Class to encapsulate all of the image processing for particle identification.
Constructor & Destructor Documentation
iden::Iden::Iden (const utilities::Md_store & in) inline
iden::Iden::~Iden () inline
Member Function Documentation
Wrapper_i_plu * Iden::fill_wrapper (unsigned int frames = 0, unsigned int start = 0)
Deprecated:
don't use this
References utilities::Md_store::add_element(), iden::Wrapper_i_plu::add_frame_data(), iden::BandPass_2D(), utilities::Md_store::contains_key(), iden::FindLocalMax_2D(), utilities::Md_store::get_value(), iden::ParticleStatistics(), iden::RecenterImage(), iden::Image2D::set_data(), utilities::Wrapper_in::set_Md_store(), utilities::Wrapper_in::set_Md_store_size(), and iden::Image2D::trim_max().
Wrapper_i_plu * Iden::fill_wrapper_avg (unsigned int frames = 0, unsigned int start = 0)
Deprecated:
don't use this
References iden::Image2D::add_data(), utilities::Md_store::add_element(), iden::Wrapper_i_plu::add_frame_data(), iden::BandPass_2D(), iden::FindLocalMax_2D(), utilities::Md_store::get_value(), iden::Wrapper_i_plu::get_value(), iden::ParticleStatistics(), iden::RecenterImage(), iden::Image2D::set_data(), utilities::Wrapper_in::set_Md_store(), utilities::Wrapper_in::set_Md_store_size(), and iden::Image2D::trim_max().
void Iden::process_frame (const Image2D & img_in, unsigned int frame_number, const utilities::Md_store * md_store_in, Wrapper_i_plu & wrapper_out) const
References utilities::Md_store::add_elements(), iden::Wrapper_i_plu::add_frame_data(), iden::BandPass_2D(), iden::FindLocalMax_2D(), iden::Image2D::get_height(), iden::Image2D::get_width(), iden::ParticleStatistics(), iden::RecenterImage(), and utilities::Wrapper_in::set_Md_store().
void iden::Iden::process_frames (const Image_base & imgs, unsigned int start_frame, unsigned int frames, Wrapper_i_plu & wrapper_out) const
void iden::Iden::process_frames_avg (const Image_base & imgs, unsigned int avg_count, unsigned int start_frame, unsigned int frames, Wrapper_i_plu & wrapper_out) const
void Iden::set_image_src (Image_base * image)
Deprecated:
don't use this
Referenced by main().
void Iden::set_md_parser (MD_parser * parser)
void Iden::set_params (const utilities::Md_store & param_in)
Set the parameters used by this iden object to extract features.
Member Data Documentation
Image_base* iden::Iden::img_src_ private
The source of the images to process.
utilities::Md_store iden::Iden::params_ private
Parameter object, holds the parameters for the image processing.
MD_parser* iden::Iden::parser_ private
Parser for metadata.
The documentation for this class was generated from the following files:
iden/include/iden.h
iden/cxx/iden.cpp