Particle Identification and Tracking: utilities::Filter_ers Class Reference
utilities::Filter_ers Class Reference
A basic filter, does rg (top), shift (top) and eccentricity (top) cuts.
#include <filter.h>
Public Member Functions
bool operator() (int ind, int frame) const
Returns true if the particle at index in frame passes what every criteria that the subclasses implement.
Filter_ers ()
Constructor.
void init (const Md_store &md_store)
Initialization from an Md_store.
void set_wrapper (const Wrapper_in *w_i)
Sets pointer to Wrapper_in to read data from.
FILT_TYPE get_type () const
Returns filter type.
Md_store get_parameters () const
Returns the filter parameters in a md_store object.
~Filter_ers ()
Destructor.
Private Attributes
float e_cut_
Eccentricity threshold.
float rg_cut_
Radius of gyration threshold.
float shift_cut_
Centroid shift threshold.
float shift_cut_sqr_
Centroid shift threshold.
const Wrapper_in * wrap_
Wrapper to read particle data from.
Detailed Description
A basic filter, does rg (top), shift (top) and eccentricity (top) cuts.
Constructor & Destructor Documentation
Filter_ers::Filter_ers ()
Constructor.
utilities::Filter_ers::~Filter_ers () inline
Destructor.
Member Function Documentation
Md_store Filter_ers::get_parameters () const
Returns the filter parameters in a md_store object.
References utilities::Md_store::add_element(), e_cut_, rg_cut_, and shift_cut_.
Referenced by main().
FILT_TYPE utilities::Filter_ers::get_type () const inline virtual
Returns filter type.
Implements utilities::Filter.
References utilities::FILT_ERS.
void Filter_ers::init (const Md_store & md_store)
Initialization from an Md_store.
References e_cut_, utilities::Md_store::get_value(), rg_cut_, shift_cut_, and shift_cut_sqr_.
Referenced by utilities::filter_factory(), and main().
bool Filter_ers::operator() (int index, int frame) const virtual
Returns true if the particle at index in frame passes what every criteria that the subclasses implement.
Implements utilities::Filter.
References utilities::D_DX, utilities::D_DY, utilities::D_E, utilities::D_R2, e_cut_, utilities::Wrapper_in::get_value(), rg_cut_, shift_cut_sqr_, and wrap_.
void utilities::Filter_ers::set_wrapper (const Wrapper_in *) inline virtual
Sets pointer to Wrapper_in to read data from.
Implements utilities::Filter.
References wrap_.
Member Data Documentation
float utilities::Filter_ers::e_cut_ private
Eccentricity threshold.
Referenced by get_parameters(), init(), and operator()().
float utilities::Filter_ers::rg_cut_ private
Radius of gyration threshold.
Referenced by get_parameters(), init(), and operator()().
float utilities::Filter_ers::shift_cut_ private
Centroid shift threshold.
Referenced by get_parameters(), and init().
float utilities::Filter_ers::shift_cut_sqr_ private
Centroid shift threshold.
Referenced by init(), and operator()().
const Wrapper_in* utilities::Filter_ers::wrap_ private
Wrapper to read particle data from.
Referenced by operator()(), and set_wrapper().
The documentation for this class was generated from the following files:
common_src/include/filter.h
common_src/cxx/filter_classes.cpp