Particle Identification and Tracking: tracking::Accum_sofq_ND Class Reference
tracking::Accum_sofq_ND Class Reference
Computes .
#include <accum_sofq_ND.h>
Public Member Functions
void add_particle (const particle *)
Adds a particle.
void out_to_wrapper (utilities::Generic_wrapper &, const utilities::Md_store &md_store) const
outputs the result of the computation to the wrapper
Accum_sofq_ND (const utilities::Tuplef &max_q, const utilities::Tuplei &n_bins)
constructor,will gain arguments
~Accum_sofq_ND ()
void get_magnitude (utilities::ND_Array< float, utilities::Tuplei::length_ > &) const
Returns an array with the magnitudes of the complex s(q) values.
void display () const
Plots the result using gnuplot.
const utilities::Tuplei & get_n_bins () const
Returns the dimensions of bins.
Private Member Functions
bool step_indx (utilities::Tuplei &indx) const
iterate through elements of arrays
Private Attributes
const utilities::Tuplei n_bins_
number of bins
utilities::Tuplef max_range_
maximum range
int total_bins_
Total number of bins.
utilities::ND_Array
< utilities::Tuplef,
utilities::Tuplei::length_ > q_
Array to hold the q-values.
utilities::ND_Array
< std::complex< float >
, utilities::Tuplei::length_ > s_of_q_
Array to hold the values.
std::string name_
name of group for writing out to a wrapper
int parts_added_
count of the number of particles added
std::string fname_
File name of data source.
int dset_
Data set number.
int comp_num_
Computation number.
Static Private Attributes
static const int rank_ = utilities::ND_Array<utilities::Tuplef,utilities::Tuplei::length_>::rank_
Rank of array.
Detailed Description
Computes .
Constructor & Destructor Documentation
Accum_sofq_ND::Accum_sofq_ND (const utilities::Tuplef & max_q, const utilities::Tuplei & n_bins)
constructor,will gain arguments
References max_range_, n_bins_, q_, and step_indx().
Accum_sofq_ND::~Accum_sofq_ND ()
Member Function Documentation
void Accum_sofq_ND::add_particle (const particle *) virtual
Adds a particle.
The sub class determines what is computed from the particle.
Implements tracking::Accumulator.
References tracking::particle_base::get_position(), pi, q_, s_of_q_, and total_bins_.
void Accum_sofq_ND::display () const
Plots the result using gnuplot.
References get_magnitude(), n_bins_, rank_, and step_indx().
Referenced by main().
void Accum_sofq_ND::get_magnitude (utilities::ND_Array< float, utilities::Tuplei::length_ > &) const
Returns an array with the magnitudes of the complex s(q) values.
References s_of_q_, and step_indx().
Referenced by display().
const utilities::Tuplei& tracking::Accum_sofq_ND::get_n_bins () const inline
Returns the dimensions of bins.
References n_bins_.
void Accum_sofq_ND::out_to_wrapper (utilities::Generic_wrapper & , const utilities::Md_store & md_store) const virtual
outputs the result of the computation to the wrapper
Implements tracking::Accumulator.
bool Accum_sofq_ND::step_indx (utilities::Tuplei & indx) const private
iterate through elements of arrays
References n_bins_, and rank_.
Referenced by Accum_sofq_ND(), display(), and get_magnitude().
Member Data Documentation
int tracking::Accum_sofq_ND::comp_num_ private
Computation number.
int tracking::Accum_sofq_ND::dset_ private
Data set number.
std::string tracking::Accum_sofq_ND::fname_ private
File name of data source.
utilities::Tuplef tracking::Accum_sofq_ND::max_range_ private
maximum range
Referenced by Accum_sofq_ND().
const utilities::Tuplei tracking::Accum_sofq_ND::n_bins_ private
number of bins
Referenced by Accum_sofq_ND(), display(), get_n_bins(), and step_indx().
std::string tracking::Accum_sofq_ND::name_ private
name of group for writing out to a wrapper
int tracking::Accum_sofq_ND::parts_added_ private
count of the number of particles added
utilities::ND_Array<utilities::Tuplef,utilities::Tuplei::length_> tracking::Accum_sofq_ND::q_ private
Array to hold the q-values.
Referenced by Accum_sofq_ND(), and add_particle().
const int tracking::Accum_sofq_ND::rank_ = utilities::ND_Array<utilities::Tuplef,utilities::Tuplei::length_>::rank_ static private
Rank of array.
Referenced by display(), and step_indx().
utilities::ND_Array<std::complex<float>,utilities::Tuplei::length_> tracking::Accum_sofq_ND::s_of_q_ private
Array to hold the values.
Referenced by add_particle(), and get_magnitude().
int tracking::Accum_sofq_ND::total_bins_ private
Total number of bins.
Referenced by add_particle().
The documentation for this class was generated from the following files:
common_src/include/accum_sofq_ND.h
common_src/cxx/accum_sofq_ND.cpp