Particle Identification and Tracking: tracking::TA_msd Class Reference
tracking::TA_msd Class Reference
Track accumulator that implements computation of the mean squared displacement.
#include <ta_msd.h>
Public Member Functions
void add_disp (const utilities::Tuplef &displacement, unsigned steps)
Add a track segment displacement.
unsigned max_step () const
Returns the maximum step that the accumulator can deal with.
TA_msd (unsigned max_steps)
Constructor.
~TA_msd ()
Destructor.
void output_to_wrapper (utilities::Generic_wrapper &out, const utilities::Md_store &md_store) const
Output function.
Private Attributes
std::vector< float > summed_displacement_
vector of Histogram objects, one for each time step, for displacement along x.
std::vector< unsigned int > segment_count_
vector of Histogram objects, one for each time step, for displacement along y.
unsigned max_step_
Maximum time step.
Detailed Description
Track accumulator that implements computation of the mean squared displacement.
Constructor & Destructor Documentation
TA_msd::TA_msd (unsigned max_steps)
Constructor.
TA_msd::~TA_msd ()
Destructor.
Member Function Documentation
void TA_msd::add_disp (const utilities::Tuplef & displacement, unsigned steps) virtual
Add a track segment displacement.
Parameters
[in] displacement The net displacement of the track segment.
[in] steps The number of time steps in the track segment.
Implements tracking::Trk_accumulator.
References max_step_, segment_count_, and summed_displacement_.
unsigned tracking::TA_msd::max_step () const inline virtual
Returns the maximum step that the accumulator can deal with.
Implements tracking::Trk_accumulator.
References max_step_.
void TA_msd::output_to_wrapper (utilities::Generic_wrapper & out, const utilities::Md_store & md_store) const
Output function.
References utilities::Generic_wrapper::add_dset(), utilities::Generic_wrapper::add_meta_data(), utilities::Generic_wrapper::close_group(), utilities::Generic_wrapper::close_wrapper(), utilities::format_name(), utilities::Md_store::get_value(), utilities::Generic_wrapper::is_open(), max_step_, utilities::Generic_wrapper::open_group(), utilities::Generic_wrapper::open_wrapper(), segment_count_, summed_displacement_, utilities::V_FLOAT, and utilities::V_INT.
Referenced by main().
Member Data Documentation
unsigned tracking::TA_msd::max_step_ private
Maximum time step.
Referenced by add_disp(), max_step(), and output_to_wrapper().
std::vector<unsigned int> tracking::TA_msd::segment_count_ private
vector of Histogram objects, one for each time step, for displacement along y.
Referenced by add_disp(), and output_to_wrapper().
std::vector<float> tracking::TA_msd::summed_displacement_ private
vector of Histogram objects, one for each time step, for displacement along x.
Referenced by add_disp(), and output_to_wrapper().
The documentation for this class was generated from the following files:
common_src/include/ta_msd.h
common_src/cxx/ta_msd.cpp