Particle Identification and Tracking: iden::Image2D Class Reference
iden::Image2D Class Reference
#include <image1.h>
Public Member Functions
Image2D ()
Image2D (const int image_length, const int image_width)
Image2D (const Image2D &other)
Image2D (const float *IN_ARRAY2, int DIM1, int DIM2)
~Image2D ()
int getx (const int index1D)
given the index of image data, returns x-position in pixels
int gety (const int index1D)
given the index of image data, returns y-position in pixels
int get1Dindex (const int x, const int y)
given x and y, return 1-dim index of image
void set_data (const Image_base &image)
Fill the image with data from an Image_base object.
void add_data (const Image_base &image)
Accumulate data from an Image_base object.
void set_data (const float *IN_ARRAY2, int DIM1, int DIM2)
Fill the image with data from an Image_base object.
void add_data (const float *IN_ARRAY2, int DIM1, int DIM2)
Accumulate data from an Image_base object.
Ipp32f * get_image2D () const
let the outside world see the pointer, get rid of this eventually? or make it safer.
int get_stepsize () const
int get_width () const
int get_numberofpixels () const
int get_height () const
IppiSize get_ROIfull () const
void display_image () const
Display the image, scaled to 8bit, using the gnuplot pipes wrapper.
void trim_max (float cut_percent)
Private Member Functions
void proc_data (const Image_base &image, bool add)
Private helper function to deal with taking in data from Image_base objects.
Private Attributes
Ipp32f * imagedata_
actual image data in Ipp32f format
unsigned int stepsize_
stepsize for use with IPP functions (step size in bytes)
unsigned int width_
width of image, in pixels
unsigned int height_
length (or height) of image, in pixels
unsigned int numberofpixels_
total number of pixels in image
IppiSize ROIfull_
ROI of the full image, used in IPP functions, when including whole image.
Constructor & Destructor Documentation
iden::Image2D::Image2D ()
Image2D::Image2D (const int image_length, const int image_width)
References height_, imagedata_, numberofpixels_, ROIfull_, stepsize_, and width_.
Image2D::Image2D (const Image2D & other)
References imagedata_, numberofpixels_, ROIfull_, and stepsize_.
iden::Image2D::Image2D (const float * IN_ARRAY2, int DIM1, int DIM2)
Image2D::~Image2D ()
References imagedata_.
Member Function Documentation
void Image2D::add_data (const Image_base & image)
Accumulate data from an Image_base object.
References proc_data().
Referenced by iden::Iden::fill_wrapper_avg().
void iden::Image2D::add_data (const float * IN_ARRAY2, int DIM1, int DIM2)
Accumulate data from an Image_base object.
void iden::Image2D::display_image () const
Display the image, scaled to 8bit, using the gnuplot pipes wrapper.
int Image2D::get1Dindex (const int x, const int y)
given x and y, return 1-dim index of image
References width_.
int iden::Image2D::get_height () const inline
References height_.
Referenced by iden::BandPass_2D(), iden::FindLocalMax_2D(), and iden::Iden::process_frame().
Ipp32f* iden::Image2D::get_image2D () const inline
let the outside world see the pointer, get rid of this eventually? or make it safer.
This will require a bunch of rewriting, sadly
References imagedata_.
Referenced by iden::BandPass_2D(), iden::FindLocalMax_2D(), and iden::RecenterImage().
int iden::Image2D::get_numberofpixels () const inline
References numberofpixels_.
IppiSize iden::Image2D::get_ROIfull () const inline
References ROIfull_.
Referenced by iden::FindLocalMax_2D(), and iden::RecenterImage().
int iden::Image2D::get_stepsize () const inline
References stepsize_.
Referenced by iden::BandPass_2D(), iden::FindLocalMax_2D(), and iden::RecenterImage().
int iden::Image2D::get_width () const inline
References width_.
Referenced by iden::BandPass_2D(), iden::FindLocalMax_2D(), and iden::Iden::process_frame().
int Image2D::getx (const int index1D)
given the index of image data, returns x-position in pixels
References width_.
int Image2D::gety (const int index1D)
given the index of image data, returns y-position in pixels
References width_.
void Image2D::proc_data (const Image_base & image, bool add) private
Private helper function to deal with taking in data from Image_base objects.
References iden::ERROR, iden::F32, iden::Image_base::get_pixel_type(), iden::Image_base::get_plane_dims(), iden::Image_base::get_plane_pixels(), iden::Image_base::get_scan_step(), height_, imagedata_, ROIfull_, iden::S16, iden::U16, iden::U8, and width_.
Referenced by add_data(), and set_data().
void Image2D::set_data (const Image_base & image)
Fill the image with data from an Image_base object.
References proc_data().
Referenced by iden::Iden::fill_wrapper(), and iden::Iden::fill_wrapper_avg().
void Image2D::set_data (const float * IN_ARRAY2, int DIM1, int DIM2)
Fill the image with data from an Image_base object.
References height_, imagedata_, numberofpixels_, ROIfull_, stepsize_, and width_.
void Image2D::trim_max (float cut_percent)
References imagedata_, numberofpixels_, ROIfull_, and stepsize_.
Referenced by iden::Iden::fill_wrapper(), and iden::Iden::fill_wrapper_avg().
Member Data Documentation
unsigned int iden::Image2D::height_ private
length (or height) of image, in pixels
Referenced by get_height(), Image2D(), proc_data(), and set_data().
Ipp32f* iden::Image2D::imagedata_ private
actual image data in Ipp32f format
Referenced by get_image2D(), Image2D(), proc_data(), set_data(), trim_max(), and ~Image2D().
unsigned int iden::Image2D::numberofpixels_ private
total number of pixels in image
Referenced by get_numberofpixels(), Image2D(), set_data(), and trim_max().
IppiSize iden::Image2D::ROIfull_ private
ROI of the full image, used in IPP functions, when including whole image.
Referenced by get_ROIfull(), Image2D(), proc_data(), set_data(), and trim_max().
unsigned int iden::Image2D::stepsize_ private
stepsize for use with IPP functions (step size in bytes)
Referenced by get_stepsize(), Image2D(), set_data(), and trim_max().
unsigned int iden::Image2D::width_ private
width of image, in pixels
Referenced by get1Dindex(), get_width(), getx(), gety(), Image2D(), proc_data(), and set_data().
The documentation for this class was generated from the following files:
iden/include/image1.h
iden/cxx/image1.cpp