Particle Identification and Tracking: iden::Image_base Class Reference
iden::Image_base Class Reference abstract
This is an ABC for different file layouts, ie to make dealing with multi-part files and the spew that comes out of stream to disk easy to change between.
#include <image_base.h>
Public Member Functions
Image_base ()
Empty constructor.
virtual ~Image_base ()
empty destructor
virtual void select_plane (unsigned int plane)=0
Set the plane w.
virtual const void * get_plane_pixels () const =0
Returns the data of the current plane.
virtual utilities::Md_store * get_plane_md (const MD_parser &parser) const =0
Returns the current plane's meta data.
virtual utilities::Tuple
< unsigned int, 2 > get_plane_dims () const =0
Returns the plane dimensions.
virtual WORD get_scan_step () const =0
returns the plane scan_step
virtual int get_frame_count () const =0
Returns the number of planes in the image.
virtual PIX_TYPE get_pixel_type () const =0
Returns the size of the image pixels.
Detailed Description
This is an ABC for different file layouts, ie to make dealing with multi-part files and the spew that comes out of stream to disk easy to change between.
Th
Constructor & Destructor Documentation
iden::Image_base::Image_base () inline
Empty constructor.
virtual iden::Image_base::~Image_base () inline virtual
empty destructor
Member Function Documentation
virtual int iden::Image_base::get_frame_count () const pure virtual
Returns the number of planes in the image.
Implemented in iden::Image_series, and iden::Image_stack.
virtual PIX_TYPE iden::Image_base::get_pixel_type () const pure virtual
Returns the size of the image pixels.
Implemented in iden::Image_series, and iden::Image_stack.
Referenced by iden::Image2D::proc_data().
virtual utilities::Tuple<unsigned int,2> iden::Image_base::get_plane_dims () const pure virtual
Returns the plane dimensions.
Implemented in iden::Image_series, and iden::Image_stack.
Referenced by iden::Image2D::proc_data().
virtual utilities::Md_store* iden::Image_base::get_plane_md (const MD_parser & parser) const pure virtual
Returns the current plane's meta data.
Returns a pointer that needs to be cleaned up.
Implemented in iden::Image_series, and iden::Image_stack.
virtual const void* iden::Image_base::get_plane_pixels () const pure virtual
Returns the data of the current plane.
This pointer is managed internally and should not be deleted. This pointer is only good until the object is closed or until the plane is changed, which ever comes first. To determine how to cast this pointer call get_pixel_type.
Implemented in iden::Image_series, and iden::Image_stack.
Referenced by iden::Image2D::proc_data().
virtual WORD iden::Image_base::get_scan_step () const pure virtual
returns the plane scan_step
Implemented in iden::Image_series, and iden::Image_stack.
Referenced by iden::Image2D::proc_data().
virtual void iden::Image_base::select_plane (unsigned int plane) pure virtual
Set the plane w.
Implemented in iden::Image_series, and iden::Image_stack.
The documentation for this class was generated from the following file:
iden/include/image_base.h