Particle Identification and Tracking: tracking::Corr_goftheta Class Reference
tracking::Corr_goftheta Class Reference abstract
simple computation.
#include <corr_goftheta.h>
Public Member Functions
void compute (const particle *, const std::vector< const particle * > &)
takes in a particle_base object.
void out_to_wrapper (utilities::Generic_wrapper &, const std::string &name) const
Corr_goftheta (int bins, float max, std::string &)
constructor.
void display () const
Displays plot of .
float get_max_range () const
Get the maximum range.
void normalize (std::vector< float > &out) const
normalizes to the average bin count
virtual void out_to_wrapper (utilities::Generic_wrapper &, const std::string &, const utilities::Md_store *) const =0
outputs the result of the computation to the wrapper
void add_plane_temperature (float temp)
Adds the temperature for a plane.
Protected Attributes
float temperature_sum_
The sum of the temperatures added.
unsigned int plane_count_
Count of the number of planes added.
Private Member Functions
void trim_nhood (const particle *p_in, const std::vector< const particle * > &nhood_in, std::vector< const particle * > &nhood_out) const
trims vectors to only include particles close enough to care about them
Private Attributes
std::vector< int > bin_count_
gives the number entries in the bin
std::vector< float > bin_edges_
gives the value of the bottom edge of the bin
unsigned int n_bins_
number of bins
float max_range_
maximum range
std::string name_
name of group for writing out to a wrapper
int parts_added_
count of the number of particles added
Detailed Description
simple computation.
This is the three-point correlation function of opening angle of two particles around a joint particle.
Constructor & Destructor Documentation
Corr_goftheta::Corr_goftheta (int bins, float max, std::string & name)
constructor.
The maximum range is taken from particle::max_neighborhood_range_. The bins are spaced linearly.
References bin_count_, bin_edges_, n_bins_, and pi.
Member Function Documentation
void Corr::add_plane_temperature (float temp) inherited
Adds the temperature for a plane.
References tracking::Corr::plane_count_, and tracking::Corr::temperature_sum_.
Referenced by tracking::Hash_shelf::compute_corr().
void Corr_goftheta::compute (const particle * , const std::vector< const particle * > &) virtual
takes in a particle_base object.
For correlations that need the tracking information this should throw an error or something clever like that
Implements tracking::Corr.
References bin_count_, tracking::particle_base::get_position(), utilities::Tuple< T, length >::make_unit(), n_bins_, parts_added_, pi, and trim_nhood().
void Corr_goftheta::display () const
Displays plot of .
References bin_edges_, and normalize().
float tracking::Corr_goftheta::get_max_range () const inline virtual
Get the maximum range.
Implements tracking::Corr.
References max_range_.
void Corr_goftheta::normalize (std::vector< float > & out) const
normalizes to the average bin count
References bin_count_, and n_bins_.
Referenced by display(), and out_to_wrapper().
void Corr_goftheta::out_to_wrapper (utilities::Generic_wrapper & in, const std::string & name) const
References utilities::Generic_wrapper::add_dset(), bin_edges_, utilities::Generic_wrapper::close_wrapper(), n_bins_, normalize(), utilities::Generic_wrapper::open_group(), utilities::Generic_wrapper::open_wrapper(), and utilities::V_FLOAT.
Referenced by main().
virtual void tracking::Corr::out_to_wrapper (utilities::Generic_wrapper & , const std::string & , const utilities::Md_store *) const pure virtual inherited
outputs the result of the computation to the wrapper
Implemented in tracking::Dummy_corr, tracking::Corr_pair_diffusion, tracking::Corr_theta_2pt, and tracking::Corr_gofr.
void Corr_goftheta::trim_nhood (const particle * p_in, const std::vector< const particle * > & nhood_in, std::vector< const particle * > & nhood_out) const private
trims vectors to only include particles close enough to care about them
References tracking::particle_base::distancesq(), and max_range_.
Referenced by compute().
Member Data Documentation
std::vector<int> tracking::Corr_goftheta::bin_count_ private
gives the number entries in the bin
Referenced by compute(), Corr_goftheta(), and normalize().
std::vector<float> tracking::Corr_goftheta::bin_edges_ private
gives the value of the bottom edge of the bin
Referenced by Corr_goftheta(), display(), and out_to_wrapper().
float tracking::Corr_goftheta::max_range_ private
maximum range
Referenced by get_max_range(), and trim_nhood().
unsigned int tracking::Corr_goftheta::n_bins_ private
number of bins
Referenced by compute(), Corr_goftheta(), normalize(), and out_to_wrapper().
std::string tracking::Corr_goftheta::name_ private
name of group for writing out to a wrapper
int tracking::Corr_goftheta::parts_added_ private
count of the number of particles added
Referenced by compute().
unsigned int tracking::Corr::plane_count_ protected inherited
Count of the number of planes added.
Referenced by tracking::Corr::add_plane_temperature(), tracking::Corr_gofr::out_to_wrapper(), and tracking::Corr_theta_2pt::out_to_wrapper().
float tracking::Corr::temperature_sum_ protected inherited
The sum of the temperatures added.
Referenced by tracking::Corr::add_plane_temperature(), tracking::Corr_gofr::out_to_wrapper(), and tracking::Corr_theta_2pt::out_to_wrapper().
The documentation for this class was generated from the following files:
common_src/include/corr_goftheta.h
common_src/cxx/corr_display.cpp
common_src/cxx/corr_goftheta.cpp