Particle Identification and Tracking: tracking::hash_box Class Reference
tracking::hash_box Class Reference
Class for storing particles in the hash table.
#include <hash_box.h>
Public Member Functions
void pass_fun_to_part (void(particle::*fun)())
Passes functions down the pyramid, this one for void, argument-less functions noncosnst.
void pass_fun_to_part (void(particle::*fun)() const) const
Passes functions down the pyramid, this one for void, argument-less functions const.
void output_to_wrapper (utilities::Wrapper_out &wrapper) const
loops over particles to
void compute_corr (tracking::Corr &) const
passes a Corr object down the pyramid
void compute_accum (Accumulator &in) const
Passes an Accumulator object down the pyramid.
over all control
Constructors, destructor, and clear all data
hash_box (const Hash_shelf *in, int hash_indx, bool own_part)
constructor with Hash_shelf information
hash_box ()
empty constructor
~hash_box ()
Destructor. Clears all the pointers to try and avoid stale pointers.
void clear ()
clears all the pointers, but doesn't destroy the box.
void push (particle *next)
add next particle
void append (hash_box *next)
appends the box 'next' to this box.
void print ()
prints out a representation of this in some useful way
Getter Functions
int get_size ()
Returns the size of the box, ie number of particles.
void get_val_vec (std::vector< float > &vec, utilities::D_TYPE type)
Returns a vector of the data of p_vals type for the box.
std::vector< particle * >::iterator begin ()
Returns an iterator to the front of the contents vector, a-la the vector.begin() function.
std::vector< particle * >
::const_iterator begin () const
a very const version
std::vector< particle * >::iterator end ()
Returns an iterator to past the end of the contents vector, a-la the vector.end() function.
void box_to_list (std::list< particle * > &p_list) const
A safer version of converting a hash_box to a list.
Protected Attributes
std::vector< particle * > contents_
Contents of the box.
const Hash_shelf * shelf_
pointer to the Hash_shelf that contains this box
int hash_indx_
position in hash shelf
bool owns_particles_
If the hash box owns the particles or not.
Detailed Description
Class for storing particles in the hash table.
This class will hold a list of the particle set in part_def.h. The primary purpose of this class is to sit in a shelf that corresponds to a hash table of the data. It can also be used to be passed out of shelf functions as a list of the particles selected, however this is confusing and should not be done.
Todo:
rename to proper capitalization
Constructor & Destructor Documentation
tracking::hash_box::hash_box (const Hash_shelf * in, int hash_indx, bool own_part) inline
constructor with Hash_shelf information
tracking::hash_box::hash_box () inline
empty constructor
hash_box::~hash_box ()
Destructor. Clears all the pointers to try and avoid stale pointers.
References contents_, and owns_particles_.
Member Function Documentation
void hash_box::append (hash_box * next)
appends the box 'next' to this box.
References contents_.
Referenced by tracking::Hash_shelf::get_region().
std::vector<particle*>::iterator tracking::hash_box::begin () inline
Returns an iterator to the front of the contents vector, a-la the vector.begin() function.
Todo:
change hash_shelf::get_region() to not use this, then remove this
References contents_.
Referenced by tracking::Hash_shelf::get_region().
std::vector<particle*>::const_iterator tracking::hash_box::begin () const inline
a very const version
Todo:
remove this
References contents_.
void hash_box::box_to_list (std::list< particle * > & p_list) const
A safer version of converting a hash_box to a list.
References contents_.
Referenced by tracking::hash_case::fill_pos_link_next().
void tracking::hash_box::clear () inline
clears all the pointers, but doesn't destroy the box.
References contents_.
Referenced by tracking::hash_case::fill_pos_link_next().
void hash_box::compute_accum (Accumulator & in) const
Passes an Accumulator object down the pyramid.
References tracking::Accumulator::add_particle(), and contents_.
void hash_box::compute_corr (tracking::Corr & in) const
passes a Corr object down the pyramid
References tracking::Corr::compute(), contents_, tracking::Corr::get_max_range(), tracking::particle_base::get_neighborhood_range(), tracking::Hash_shelf::get_region_px(), hash_indx_, and shelf_.
std::vector<particle*>::iterator tracking::hash_box::end () inline
Returns an iterator to past the end of the contents vector, a-la the vector.end() function.
figure out who uses this function is used and make private or kill
References contents_.
Referenced by tracking::Hash_shelf::get_region().
int tracking::hash_box::get_size () inline
Returns the size of the box, ie number of particles.
References contents_.
void tracking::hash_box::get_val_vec (std::vector< float > & vec, utilities::D_TYPE type)
Returns a vector of the data of p_vals type for the box.
void hash_box::output_to_wrapper (utilities::Wrapper_out & wrapper) const
loops over particles to
References contents_, and utilities::Wrapper_out::set_all_values().
void hash_box::pass_fun_to_part (void(particle::*)() fun)
Passes functions down the pyramid, this one for void, argument-less functions noncosnst.
References contents_.
void hash_box::pass_fun_to_part (void(particle::*)() const fun) const
Passes functions down the pyramid, this one for void, argument-less functions const.
References contents_.
void hash_box::print ()
prints out a representation of this in some useful way
References contents_.
void tracking::hash_box::push (particle * next) inline
add next particle
References contents_.
Referenced by tracking::Hash_shelf::push().
Member Data Documentation
std::vector<particle*> tracking::hash_box::contents_ protected
Contents of the box.
Referenced by append(), begin(), box_to_list(), clear(), compute_accum(), compute_corr(), end(), get_size(), output_to_wrapper(), pass_fun_to_part(), print(), push(), and ~hash_box().
int tracking::hash_box::hash_indx_ protected
position in hash shelf
Referenced by compute_corr().
bool tracking::hash_box::owns_particles_ protected
If the hash box owns the particles or not.
Referenced by ~hash_box().
const Hash_shelf* tracking::hash_box::shelf_ protected
pointer to the Hash_shelf that contains this box
Referenced by compute_corr().
The documentation for this class was generated from the following files:
common_src/include/hash_box.h
common_src/cxx/corr.cpp
common_src/cxx/function_cascades.cpp
common_src/cxx/hash_box.cpp