Particle Identification and Tracking: utilities::Generic_wrapper Class Reference
utilities::Generic_wrapper Class Reference abstract
An interface for extracting data from the internal data structures.
#include <generic_wrapper.h>
Public Member Functions
virtual ~Generic_wrapper ()
Destructor.
Wrapper state
Change and query the top level wrapper state
virtual void open_wrapper ()=0
Initializes the wrapper.
virtual void close_wrapper ()=0
closes and cleans up the wrapper
virtual bool is_open () const =0
Returns if the wrapper is open or not.
Group state
Change and query the wrapper current group state
virtual void open_group (const std::string &name="none")=0
Opens a group in the wrapper, ie a group in hdf or a cell in matlab.
virtual void close_group ()=0
closes the current group
Data
get and set data
virtual void add_dset (int rank, const unsigned int *dims, V_TYPE vt, const void *data, const std::string &dset_name)=0
Adds data to the wrapper, must be the right size and type specified.
Group Level Metadata
setter functions for metadata for the currently open group.
virtual void add_meta_data (const std::string &key, float val)=0
Adds a float meta-data.
virtual void add_meta_data (const std::string &key, const Tuple< float, 3 > &val)=0
Adds a Triple meta-data.
virtual void add_meta_data (const std::string &key, const Tuple< float, 2 > &val)=0
Adds a Pair meta-data.
virtual void add_meta_data (const std::string &key, const std::string &val)=0
Adds a string meta-data.
virtual void add_meta_data (const std::string &key, int val)=0
Adds an integer meta-data.
virtual void add_meta_data (const std::string &key, unsigned int val)=0
Adds an unsigned integer meta-data.
virtual void add_meta_data (const Md_store *md_store)=0
Adds all the meta data in a Md_store at the group level.
Dataset Level Metadata
setter functions for metadata for the named dataset.
virtual void add_meta_data (const std::string &key, float val, const std::string &dset_name)=0
Adds a float meta-data for a data set.
virtual void add_meta_data (const std::string &key, const Tuple< float, 3 > &val, const std::string &dset_name)=0
Adds a Triple meta-data for a data set.
virtual void add_meta_data (const std::string &key, const Tuple< float, 2 > &val, const std::string &dset_name)=0
Adds a Pair meta-data for a data set.
virtual void add_meta_data (const std::string &key, const std::string &val, const std::string &dset_name)=0
Adds a string meta-data for a data set.
virtual void add_meta_data (const std::string &key, int val, const std::string &dset_name)=0
Adds an integer meta-data for a data set.
virtual void add_meta_data (const std::string &key, unsigned int val, const std::string &dset_name)=0
Adds an unsigned integer meta-data for a data set.
virtual void add_meta_data (const Md_store *md_store, const std::string &dset_name)=0
Adds all the meta data in a Md_store at the dset level.
Detailed Description
An interface for extracting data from the internal data structures.
IE, this object gets handed to the internal objects, and they fill it with data.
This is an abstract base class/interface.
Constructor & Destructor Documentation
virtual utilities::Generic_wrapper::~Generic_wrapper () inline virtual
Destructor.
Member Function Documentation
virtual void utilities::Generic_wrapper::add_dset (int rank, const unsigned int * dims, V_TYPE vt, const void * data, const std::string & dset_name) pure virtual
Adds data to the wrapper, must be the right size and type specified.
data will be written safely with in the wrapper during this call so it can be safely freed outside if needed
Parameters
[in] rank rank of data set
[in] dimensions of data set
[in] vt data type
[in] data pointer to data to be set
[in] dset_name name of data set
Implemented in utilities::Generic_wrapper_hdf.
Referenced by tracking::Accum_sofq::out_to_wrapper(), tracking::Accum_chi4_self::out_to_wrapper(), tracking::Corr_goftheta::out_to_wrapper(), tracking::Corr_gofr::out_to_wrapper(), utilities::Counted_vector::output_to_wrapper(), tracking::TA_msd::output_to_wrapper(), utilities::Histogram::output_to_wrapper(), and tracking::Track_shelf::output_to_wrapper().
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, float val) pure virtual
Adds a float meta-data.
Implemented in utilities::Generic_wrapper_hdf.
Referenced by tracking::Accum_sofq::out_to_wrapper(), tracking::Corr_gofr::out_to_wrapper(), tracking::Corr_theta_2pt::out_to_wrapper(), tracking::Corr_pair_diffusion::out_to_wrapper(), tracking::Corr_case::out_to_wrapper(), utilities::Counted_vector::output_to_wrapper(), tracking::TA_vanHove::output_to_wrapper(), tracking::TA_disp::output_to_wrapper(), tracking::TA_theta_rlim::output_to_wrapper(), tracking::TA_msd::output_to_wrapper(), utilities::Histogram::output_to_wrapper(), and tracking::Track_shelf::output_to_wrapper().
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, const Tuple< float, 3 > & val) pure virtual
Adds a Triple meta-data.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, const Tuple< float, 2 > & val) pure virtual
Adds a Pair meta-data.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, const std::string & val) pure virtual
Adds a string meta-data.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, int val) pure virtual
Adds an integer meta-data.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, unsigned int val) pure virtual
Adds an unsigned integer meta-data.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const Md_store * md_store) pure virtual
Adds all the meta data in a Md_store at the group level.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, float val, const std::string & dset_name) pure virtual
Adds a float meta-data for a data set.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, const Tuple< float, 3 > & val, const std::string & dset_name) pure virtual
Adds a Triple meta-data for a data set.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, const Tuple< float, 2 > & val, const std::string & dset_name) pure virtual
Adds a Pair meta-data for a data set.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, const std::string & val, const std::string & dset_name) pure virtual
Adds a string meta-data for a data set.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, int val, const std::string & dset_name) pure virtual
Adds an integer meta-data for a data set.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const std::string & key, unsigned int val, const std::string & dset_name) pure virtual
Adds an unsigned integer meta-data for a data set.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::add_meta_data (const Md_store * md_store, const std::string & dset_name) pure virtual
Adds all the meta data in a Md_store at the dset level.
Implemented in utilities::Generic_wrapper_hdf.
virtual void utilities::Generic_wrapper::close_group () pure virtual
closes the current group
Implemented in utilities::Generic_wrapper_hdf.
Referenced by tracking::Corr_gofr::out_to_wrapper(), tracking::Corr_theta_2pt::out_to_wrapper(), tracking::Corr_pair_diffusion::out_to_wrapper(), tracking::Corr_case::out_to_wrapper(), utilities::Counted_vector::output_to_wrapper(), tracking::TA_vanHove::output_to_wrapper(), tracking::TA_disp::output_to_wrapper(), tracking::TA_theta_rlim::output_to_wrapper(), tracking::TA_msd::output_to_wrapper(), utilities::Histogram::output_to_wrapper(), and tracking::Track_shelf::output_to_wrapper().
virtual void utilities::Generic_wrapper::close_wrapper () pure virtual
closes and cleans up the wrapper
Implemented in utilities::Generic_wrapper_hdf.
Referenced by tracking::Accum_chi4_self::out_to_wrapper(), tracking::Corr_goftheta::out_to_wrapper(), tracking::Corr_gofr::out_to_wrapper(), tracking::Corr_theta_2pt::out_to_wrapper(), tracking::Corr_pair_diffusion::out_to_wrapper(), tracking::Corr_case::out_to_wrapper(), utilities::Counted_vector::output_to_wrapper(), tracking::TA_vanHove::output_to_wrapper(), tracking::TA_disp::output_to_wrapper(), tracking::TA_theta_rlim::output_to_wrapper(), tracking::TA_msd::output_to_wrapper(), utilities::Histogram::output_to_wrapper(), and tracking::Track_shelf::output_to_wrapper().
virtual bool utilities::Generic_wrapper::is_open () const pure virtual
Returns if the wrapper is open or not.
Implemented in utilities::Generic_wrapper_hdf.
Referenced by tracking::Accum_chi4_self::out_to_wrapper(), tracking::Corr_gofr::out_to_wrapper(), tracking::Corr_theta_2pt::out_to_wrapper(), tracking::Corr_pair_diffusion::out_to_wrapper(), utilities::Counted_vector::output_to_wrapper(), tracking::TA_vanHove::output_to_wrapper(), tracking::TA_disp::output_to_wrapper(), tracking::TA_theta_rlim::output_to_wrapper(), tracking::TA_msd::output_to_wrapper(), utilities::Histogram::output_to_wrapper(), and tracking::Track_shelf::output_to_wrapper().
virtual void utilities::Generic_wrapper::open_group (const std::string & name = "none") pure virtual
Opens a group in the wrapper, ie a group in hdf or a cell in matlab.
Implemented in utilities::Generic_wrapper_hdf.
Referenced by tracking::Accum_chi4_self::out_to_wrapper(), tracking::Corr_goftheta::out_to_wrapper(), tracking::Corr_gofr::out_to_wrapper(), tracking::Corr_theta_2pt::out_to_wrapper(), tracking::Corr_pair_diffusion::out_to_wrapper(), tracking::Corr_case::out_to_wrapper(), utilities::Counted_vector::output_to_wrapper(), tracking::TA_vanHove::output_to_wrapper(), tracking::TA_disp::output_to_wrapper(), tracking::TA_theta_rlim::output_to_wrapper(), tracking::TA_msd::output_to_wrapper(), utilities::Histogram::output_to_wrapper(), and tracking::Track_shelf::output_to_wrapper().
virtual void utilities::Generic_wrapper::open_wrapper () pure virtual
Initializes the wrapper.
Implemented in utilities::Generic_wrapper_hdf.
Referenced by tracking::Accum_chi4_self::out_to_wrapper(), tracking::Corr_goftheta::out_to_wrapper(), tracking::Corr_gofr::out_to_wrapper(), tracking::Corr_theta_2pt::out_to_wrapper(), tracking::Corr_pair_diffusion::out_to_wrapper(), tracking::Corr_case::out_to_wrapper(), utilities::Counted_vector::output_to_wrapper(), tracking::TA_vanHove::output_to_wrapper(), tracking::TA_disp::output_to_wrapper(), tracking::TA_theta_rlim::output_to_wrapper(), tracking::TA_msd::output_to_wrapper(), utilities::Histogram::output_to_wrapper(), and tracking::Track_shelf::output_to_wrapper().
The documentation for this class was generated from the following file:
common_src/include/generic_wrapper.h