Particle Identification and Tracking: tracking::Corr_pair_diffusion Class Reference
tracking::Corr_pair_diffusion Class Reference
computes the motion of a pair of particles in relation to each other.
#include <corr_pair_diffusion.h>
Public Member Functions
void compute (const particle *, const std::vector< const particle * > &)
takes in a particle_base object.
void out_to_wrapper (utilities::Generic_wrapper &wrapper_out, const std::string &g_name, const utilities::Md_store *md_store) const
outputs the result of the computation to the wrapper
Corr_pair_diffusion (unsigned int n_dbins, float max_disp, unsigned int n_rbins, float min_r, float max_r, unsigned int min_t, unsigned int t_stride, unsigned int t_step_count)
constructor.
float get_max_range () const
returns the maximum range that the Corr object looks out to.
void add_plane_temperature (float temp)
Adds the temperature for a plane.
Protected Attributes
float temperature_sum_
The sum of the temperatures added.
unsigned int plane_count_
Count of the number of planes added.
Private Attributes
std::vector< std::vector
< utilities::Histogram > > data_prll_
Main data structure.
std::vector< std::vector
< utilities::Histogram > > data_perp_
const float min_r_
const float max_r_
const unsigned int n_rbins_
const float min_r_square_
const float max_r_square_
const unsigned int min_t_
const unsigned int t_stride_
const unsigned int t_step_count_
Detailed Description
computes the motion of a pair of particles in relation to each other.
Binned by their initial separation and the wait time.
Constructor & Destructor Documentation
Corr_pair_diffusion::Corr_pair_diffusion (unsigned int n_dbins, float max_disp, unsigned int n_rbins, float min_r, float max_r, unsigned int min_t, unsigned int t_stride, unsigned int t_step_count)
constructor.
Parameters
[in] n_dbins then number of bins in displacement histogram
[in] max_disp the maximum displacement to consider
[in] n_rbins then number of bins in separation histogram
[in] min_r the minimum initial separation to consider
[in] max_r the maximum initial separation to consider
[in] min_t the minimum time lag to consider
[in] max_t the maximum time lag to consider
[in] t_step the time step to between computed frames
Member Function Documentation
void Corr::add_plane_temperature (float temp) inherited
Adds the temperature for a plane.
References tracking::Corr::plane_count_, and tracking::Corr::temperature_sum_.
Referenced by tracking::Hash_shelf::compute_corr().
void Corr_pair_diffusion::compute (const particle * , const std::vector< const particle * > &) virtual
takes in a particle_base object.
For correlations that need the tracking information this should throw an error or something clever like that
Implements tracking::Corr.
References data_perp_, data_prll_, tracking::particle_base::distancesq(), tracking::particle_track::get_corrected_disp(), tracking::particle_base::get_position(), utilities::Tuple< T, length >::make_unit(), max_r_, min_r_, min_r_square_, min_t_, n_rbins_, tracking::particle_track::step_forwards(), t_step_count_, and t_stride_.
float tracking::Corr_pair_diffusion::get_max_range () const inline virtual
returns the maximum range that the Corr object looks out to.
This is needed so that the Hash_shelf can properly limit the particles that it hands in
Implements tracking::Corr.
References max_r_square_.
void Corr_pair_diffusion::out_to_wrapper (utilities::Generic_wrapper & , const std::string & , const utilities::Md_store *) const virtual
outputs the result of the computation to the wrapper
Implements tracking::Corr.
References utilities::Generic_wrapper::add_meta_data(), utilities::Generic_wrapper::close_group(), utilities::Generic_wrapper::close_wrapper(), data_perp_, data_prll_, utilities::format_name(), utilities::Generic_wrapper::is_open(), max_r_, min_r_, min_t_, n_rbins_, utilities::Generic_wrapper::open_group(), utilities::Generic_wrapper::open_wrapper(), utilities::Md_store::set_value(), t_step_count_, and t_stride_.
Member Data Documentation
std::vector< std::vector<utilities::Histogram> > tracking::Corr_pair_diffusion::data_perp_ private
Referenced by compute(), and out_to_wrapper().
std::vector< std::vector<utilities::Histogram> > tracking::Corr_pair_diffusion::data_prll_ private
Main data structure.
2 levels of nesting, outer layer is time, inner layer is initial separation. Histogram object take care of the displacement layer.
Referenced by compute(), and out_to_wrapper().
const float tracking::Corr_pair_diffusion::max_r_ private
Referenced by compute(), and out_to_wrapper().
const float tracking::Corr_pair_diffusion::max_r_square_ private
Referenced by get_max_range().
const float tracking::Corr_pair_diffusion::min_r_ private
Referenced by compute(), and out_to_wrapper().
const float tracking::Corr_pair_diffusion::min_r_square_ private
Referenced by compute().
const unsigned int tracking::Corr_pair_diffusion::min_t_ private
Referenced by compute(), and out_to_wrapper().
const unsigned int tracking::Corr_pair_diffusion::n_rbins_ private
Referenced by compute(), and out_to_wrapper().
unsigned int tracking::Corr::plane_count_ protected inherited
Count of the number of planes added.
Referenced by tracking::Corr::add_plane_temperature(), tracking::Corr_gofr::out_to_wrapper(), and tracking::Corr_theta_2pt::out_to_wrapper().
const unsigned int tracking::Corr_pair_diffusion::t_step_count_ private
Referenced by compute(), and out_to_wrapper().
const unsigned int tracking::Corr_pair_diffusion::t_stride_ private
Referenced by compute(), and out_to_wrapper().
float tracking::Corr::temperature_sum_ protected inherited
The sum of the temperatures added.
Referenced by tracking::Corr::add_plane_temperature(), tracking::Corr_gofr::out_to_wrapper(), and tracking::Corr_theta_2pt::out_to_wrapper().
The documentation for this class was generated from the following files:
common_src/include/corr_pair_diffusion.h
common_src/cxx/corr_pair_diffusion.cpp