Particle Identification and Tracking: tracking::Corr_gofr Class Reference
tracking::Corr_gofr Class Reference
simple g(r) computation
#include <corr_gofr.h>
Public Member Functions
void compute (const particle *, const std::vector< const particle * > &)
takes in a particle_base object.
void out_to_wrapper (utilities::Generic_wrapper &, const std::string &, const utilities::Md_store *) const
outputs the result of the computation to the wrapper
float normalize (std::vector< float > &gofr) const
normalize g(r) to the average and area etc
void get_bin_edges (std::vector< float > &out) const
Returns the bin edges.
Corr_gofr (int bins, float max)
constructor.
void display () const
Display on screen using gnuplot.
float get_max_range () const
Return the maximum range.
void add_plane_temperature (float temp)
Adds the temperature for a plane.
Protected Attributes
float temperature_sum_
The sum of the temperatures added.
unsigned int plane_count_
Count of the number of planes added.
Private Attributes
std::vector< unsigned int > bin_count_
gives the number entries in the bin
std::vector< float > bin_edges_
gives the value of the bottom edge of the bin
unsigned int n_bins_
number of bins
float max_range_
maximum range
unsigned int parts_added_
count of the number of particles added
Detailed Description
simple g(r) computation
Constructor & Destructor Documentation
Corr_gofr::Corr_gofr (int bins, float max)
constructor.
The bins are spaced linearly.
References bin_count_, bin_edges_, and max_range_.
Member Function Documentation
void Corr::add_plane_temperature (float temp) inherited
Adds the temperature for a plane.
References tracking::Corr::plane_count_, and tracking::Corr::temperature_sum_.
Referenced by tracking::Hash_shelf::compute_corr().
void Corr_gofr::compute (const particle * , const std::vector< const particle * > &) virtual
takes in a particle_base object.
For correlations that need the tracking information this should throw an error or something clever like that
Implements tracking::Corr.
References bin_count_, tracking::particle_base::distancesq(), max_range_, n_bins_, and parts_added_.
void Corr_gofr::display () const
Display on screen using gnuplot.
References bin_edges_, and normalize().
void Corr_gofr::get_bin_edges (std::vector< float > & out) const
Returns the bin edges.
References bin_edges_.
float tracking::Corr_gofr::get_max_range () const inline virtual
Return the maximum range.
This might get promoted to Corr.
Implements tracking::Corr.
References max_range_.
float Corr_gofr::normalize (std::vector< float > & gofr) const
normalize g(r) to the average and area etc
References bin_count_, bin_edges_, max_range_, n_bins_, parts_added_, and pi.
Referenced by display(), and out_to_wrapper().
void Corr_gofr::out_to_wrapper (utilities::Generic_wrapper & , const std::string & , const utilities::Md_store *) const virtual
outputs the result of the computation to the wrapper
Implements tracking::Corr.
References utilities::Generic_wrapper::add_dset(), utilities::Generic_wrapper::add_meta_data(), bin_edges_, utilities::Generic_wrapper::close_group(), utilities::Generic_wrapper::close_wrapper(), utilities::Generic_wrapper::is_open(), max_range_, n_bins_, normalize(), utilities::Generic_wrapper::open_group(), utilities::Generic_wrapper::open_wrapper(), parts_added_, tracking::Corr::plane_count_, tracking::Corr::temperature_sum_, and utilities::V_FLOAT.
Referenced by main().
Member Data Documentation
std::vector<unsigned int> tracking::Corr_gofr::bin_count_ private
gives the number entries in the bin
Referenced by compute(), Corr_gofr(), and normalize().
std::vector<float> tracking::Corr_gofr::bin_edges_ private
gives the value of the bottom edge of the bin
Referenced by Corr_gofr(), display(), get_bin_edges(), normalize(), and out_to_wrapper().
float tracking::Corr_gofr::max_range_ private
maximum range
Referenced by compute(), Corr_gofr(), get_max_range(), normalize(), and out_to_wrapper().
unsigned int tracking::Corr_gofr::n_bins_ private
number of bins
Referenced by compute(), normalize(), and out_to_wrapper().
unsigned int tracking::Corr_gofr::parts_added_ private
count of the number of particles added
Referenced by compute(), normalize(), and out_to_wrapper().
unsigned int tracking::Corr::plane_count_ protected inherited
Count of the number of planes added.
Referenced by tracking::Corr::add_plane_temperature(), out_to_wrapper(), and tracking::Corr_theta_2pt::out_to_wrapper().
float tracking::Corr::temperature_sum_ protected inherited
The sum of the temperatures added.
Referenced by tracking::Corr::add_plane_temperature(), out_to_wrapper(), and tracking::Corr_theta_2pt::out_to_wrapper().
The documentation for this class was generated from the following files:
common_src/include/corr_gofr.h
common_src/cxx/corr_display.cpp
common_src/cxx/corr_gofr.cpp