Particle Identification and Tracking: common_src/cxx/corr_display.cpp File Reference
corr_display.cpp File Reference
#include "corr_gofr.h"
#include "corr_goftheta.h"
#include "gnuplot_i.hpp"
Variables
const float pi = acos(-1)
Variable Documentation
const float pi = acos(-1)
Referenced by tracking::Accum_sofq_ND::add_particle(), tracking::Corr_goftheta::compute(), tracking::Corr_goftheta::Corr_goftheta(), and tracking::Corr_gofr::normalize().