Particle Identification and Tracking: iden/testing/fi_test.cpp File Reference
fi_test.cpp File Reference
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>
#include <xercesc/dom/DOM.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMDocumentType.hpp>
#include <xercesc/dom/DOMElement.hpp>
#include <xercesc/dom/DOMImplementation.hpp>
#include <xercesc/dom/DOMImplementationLS.hpp>
#include <xercesc/dom/DOMNodeIterator.hpp>
#include <xercesc/dom/DOMNodeList.hpp>
#include <xercesc/dom/DOMText.hpp>
#include <xercesc/framework/MemBufInputSource.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>
#include <xercesc/util/XMLUni.hpp>
#include "FreeImagePlus.h"
Functions
void parse_description (string &des, vector< Config_pram > &prams_)
void parse_elements (DOMNode *pram_elm, vector< Config_pram > &prams_, XMLCh *pram_str, XMLCh *key_str, XMLCh *value_str, XMLCh *type_str)
int main ()
Variables
static string fname = "/home/tcaswell/colloids/2010/data/polyNIPAM_batch_12/2010-10-03/ssd_test/t3/test3_001.tif"
static const char * gMemBufId = "ImageDescription"
Function Documentation
int main ()
References fname, gMemBufId, and parse_elements().
void parse_description (string & des, vector< Config_pram > & prams_)
void parse_elements (DOMNode * pram_elm, vector< Config_pram > & prams_, XMLCh * pram_str, XMLCh * key_str, XMLCh * value_str, XMLCh * type_str)
References parse_description().
Referenced by main().
Variable Documentation
string fname = "/home/tcaswell/colloids/2010/data/polyNIPAM_batch_12/2010-10-03/ssd_test/t3/test3_001.tif" static
Referenced by utilities::wrapper_o_file::initialize(), utilities::Wrapper_i_hdf::initialize(), main(), utilities::Wrapper_i_jb_binary::set_file_name(), and utilities::Wrapper_i_hdf::set_file_name().
const char* gMemBufId = "ImageDescription" static
Referenced by main().