Particle Identification and Tracking: testing/filt_fac_test/filter_factory_test.cpp File Reference
filter_factory_test.cpp File Reference
#include "read_config.h"
#include "filter.h"
#include <vector>
#include <string>
#include <iostream>
Functions
int main ()
Function Documentation
int main ()
References utilities::filter_factory(), utilities::Read_config::get_store(), and utilities::Filter::get_type().