Particle Identification and Tracking: testing/generic_wrapper_test.cpp File Reference
generic_wrapper_test.cpp File Reference
#include <iostream>
#include <exception>
#include <vector>
#include <string>
#include "generic_wrapper_hdf.h"
Functions
int main (int argc, const char *argv[])
Function Documentation
int main (int argc, const char * argv[])
References utilities::Generic_wrapper_hdf::add_dset(), utilities::Generic_wrapper_hdf::close_group(), utilities::Generic_wrapper_hdf::close_wrapper(), utilities::Generic_wrapper_hdf::get_dset(), utilities::Generic_wrapper_hdf::open_group(), utilities::Generic_wrapper_hdf::open_wrapper(), utilities::V_FLOAT, utilities::V_INT, and utilities::V_UINT.