Particle Identification and Tracking: apps/gofr_by_plane.cpp File Reference
gofr_by_plane.cpp File Reference
#include <iostream>
#include <stdexcept>
#include "master_box_t.h"
#include "particle_base.h"
#include "hash_case.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "generic_wrapper_hdf.h"
#include "corr_case.h"
#include "read_config.h"
#include "cl_parse.h"
#include "enum_utils.h"
#include "sql_handler.h"
#include "md_store.h"
Functions
int main (int argc, char *argv[])
Variables
static string APP_NAME = "gofr_by_plane :: "
Function Documentation
int main (int argc, char * argv[])
References utilities::Md_store::add_element(), utilities::Md_store::add_elements(), utilities::SQL_handler::add_mdata(), utilities::SQL_handler::close_connection(), utilities::SQL_handler::commit(), tracking::hash_case::compute_corr(), utilities::Read_config::contains_key(), utilities::D_DX, utilities::D_DY, utilities::D_E, utilities::D_I, utilities::D_R2, utilities::D_XPOS, utilities::D_YPOS, utilities::extract_prams(), utilities::F_GOFR_BY_PLANE, utilities::format_name(), utilities::CL_parse::get_fpram(), tracking::hash_case::get_num_frames(), utilities::Filter_ers::get_parameters(), utilities::Read_config::get_store(), utilities::Read_config::get_value(), tracking::hash_case::init(), tracking::Master_box::init(), utilities::Filter_ers::init(), utilities::SQL_handler::open_connection(), tracking::Corr_case::out_to_wrapper(), utilities::CL_parse::parse(), tracking::Master_box::size(), and utilities::SQL_handler::start_comp().
Variable Documentation
string APP_NAME = "gofr_by_plane :: " static