Particle Identification and Tracking: apps/gofr_general.cpp File Reference
gofr_general.cpp File Reference
#include <iostream>
#include <stdexcept>
#include "master_box_t.h"
#include "particle_base.h"
#include "hash_case.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "wrapper_i_jb_binary.h"
#include "filter.h"
#include "generic_wrapper_hdf.h"
#include "corr_gofr.h"
#include "read_config.h"
#include "enum_utils.h"
#include "sql_handler.h"
#include "md_store.h"
Functions
int main (int argc, char *argv[])
Variables
static string APP_NAME = "gofr :: "
Function Documentation
int main (int argc, char * argv[])
References tracking::hash_case::compute_corr(), fname, utilities::format_name(), tracking::hash_case::init(), tracking::Corr_gofr::out_to_wrapper(), tracking::hash_case::print(), utilities::Wrapper_i_jb_binary::proc_file(), and utilities::Wrapper_i_jb_binary::set_file_name().
Variable Documentation
string APP_NAME = "gofr :: " static