Particle Identification and Tracking: apps/gofr_hdf.cpp File Reference
gofr_hdf.cpp File Reference
#include <iostream>
#include <stdexcept>
#include <getopt.h>
#include "master_box_t.h"
#include "particle_base.h"
#include "hash_case.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "generic_wrapper_hdf.h"
#include "corr_gofr.h"
#include "read_config.h"
#include "enum_utils.h"
#include "sql_handler.h"
#include "md_store.h"
Functions
int main (int argc, char *argv[])
Variables
static string APP_NAME = "gofr :: "
Function Documentation
int main (int argc, char * argv[])
References utilities::Md_store::add_element(), utilities::Md_store::add_elements(), utilities::SQL_handler::add_mdata(), APP_NAME, utilities::SQL_handler::close_connection(), utilities::SQL_handler::commit(), tracking::hash_case::compute_corr(), utilities::Read_config::contains_key(), utilities::D_DX, utilities::D_DY, utilities::D_E, utilities::D_I, utilities::D_R2, utilities::D_XPOS, utilities::D_YPOS, utilities::extract_prams(), utilities::F_GOFR, utilities::format_name(), utilities::Wrapper_i_hdf::get_dims(), utilities::Wrapper_i_hdf::get_num_frames(), utilities::Read_config::get_store(), utilities::Read_config::get_value(), tracking::hash_case::init(), tracking::Master_box::init(), utilities::Wrapper_i_hdf::initialize(), utilities::SQL_handler::open_connection(), tracking::Corr_gofr::out_to_wrapper(), tracking::Master_box::size(), and utilities::SQL_handler::start_comp().
Variable Documentation
string APP_NAME = "gofr :: " static
Referenced by main().