Particle Identification and Tracking: apps/gofr3D_hdf.cpp File Reference
gofr3D_hdf.cpp File Reference
#include "master_box_t.h"
#include "particle_base.h"
#include "hash_case.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "generic_wrapper_hdf.h"
#include "corr_gofr.h"
#include <unistd.h>
#include <vector>
#include "read_config.h"
#include <stdexcept>
Typedefs
typedef Generic_wrapper_hdf::F_TYPE F_TYPE
Functions
int main (int argc, char *const argv[])
Variables
static string APP_NAME = "gofr3D :: "
Typedef Documentation
typedef Generic_wrapper_hdf::F_TYPE F_TYPE
Function Documentation
int main (int argc, char *const argv[])
Todo:
these parameters need to be passed in
References APP_NAME, tracking::hash_case::compute_corr(), utilities::Read_config::contains_key(), utilities::D_XPOS, utilities::D_YPOS, utilities::D_ZPOS, utilities::Read_config::get_value(), tracking::hash_case::init(), tracking::Master_box::init(), tracking::Corr_gofr::out_to_wrapper(), and tracking::Master_box::size().
Variable Documentation
string APP_NAME = "gofr3D :: " static
Referenced by main().