Particle Identification and Tracking: apps/goftheta_hdf.cpp File Reference
goftheta_hdf.cpp File Reference
#include <iostream>
#include "master_box_t.h"
#include "particle_base.h"
#include "hash_case.h"
#include "triple.h"
#include "pair.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "generic_wrapper_hdf.h"
#include "corr_goftheta.h"
Functions
int main (int argc, const char *argv[])
Variables
static string base_proc_path = "/home/tcaswell/colloids/processed/"
Function Documentation
int main (int argc, const char * argv[])
References base_proc_path, tracking::hash_case::compute_corr(), utilities::D_DX, utilities::D_DY, utilities::D_E, utilities::D_I, utilities::D_MULT, utilities::D_R2, utilities::D_XPOS, utilities::D_YPOS, tracking::hash_case::init(), tracking::Master_box::init(), tracking::Corr_goftheta::out_to_wrapper(), and tracking::Master_box::size().
Variable Documentation
string base_proc_path = "/home/tcaswell/colloids/processed/" static
Referenced by main().