Particle Identification and Tracking: Life cycle of wrapper object
Life cycle of wrapper object
Order of operations on Wrapper_i_generic objects.
Functions
bool utilities::Wrapper_i_generic::open_wrapper ()
open wrapper to accept data, nukes everything currently in the wrapper
bool utilities::Wrapper_i_generic::setup (const std::set< D_TYPE > &, int N, const Tuplef &)
Sets the number of frames to expect.
bool utilities::Wrapper_i_generic::open_frame (unsigned int frame, int N, float z)
Opens a frame to add data to it.
bool utilities::Wrapper_i_generic::set_data_type (D_TYPE dtype)
Configures the object to take data of the given type.
bool utilities::Wrapper_i_generic::clear_data_type ()
Clears the current data type, no questions asked.
bool utilities::Wrapper_i_generic::add_int_data (int *data, int N)
adds data, must have an active data type set
bool utilities::Wrapper_i_generic::add_float_data (float *data, int N)
adds data, must have an active data type set
bool utilities::Wrapper_i_generic::set_meta_data (const Md_store &md_store)
Sets frame meta-data for the frame.
bool utilities::Wrapper_i_generic::close_frame ()
Closes frame.
bool utilities::Wrapper_i_generic::finalize_wrapper ()
Closes wrapper from taking any new data.
Detailed Description
Order of operations on Wrapper_i_generic objects.
Function Documentation
bool Wrapper_i_generic::add_float_data (float * data, int N)
adds data, must have an active data type set
Copies the data to it's own internal data structures so that it does not care what the source does. This is a major memory waste, but RAM is cheap.
This will clear the set data type.
will throw errors if there is not a set data type
Parameters
data the data, pointer to 1D array
N length
Returns
if it works
References utilities::Wrapper_i_generic::clear_data_type(), utilities::Wrapper_i_generic::cur_dtype_, utilities::Wrapper_i_generic::cur_frame_number_, utilities::Wrapper_i_generic::cur_frame_size_, utilities::Wrapper_i_generic::d_mapf_, utilities::Wrapper_i_generic::data_f_, utilities::V_FLOAT, and utilities::v_type().
Referenced by utilities::Wrapper_i_jb_binary::proc_file().
bool Wrapper_i_generic::add_int_data (int * data, int N)
adds data, must have an active data type set
Copies the data to it's own internal data structures so that it does not care what the source does. This is a major memory waste, but RAM is cheap.
This will clear the set data type.
will throw errors if there is not a set data type
Parameters
data the data, pointer to 1D array
N length
Returns
if it works
References utilities::Wrapper_i_generic::clear_data_type(), utilities::Wrapper_i_generic::cur_dtype_, utilities::Wrapper_i_generic::cur_frame_number_, utilities::Wrapper_i_generic::cur_frame_size_, utilities::Wrapper_i_generic::d_mapi_, utilities::Wrapper_i_generic::data_i_, utilities::V_INT, and utilities::v_type().
bool Wrapper_i_generic::clear_data_type ()
Clears the current data type, no questions asked.
References utilities::Wrapper_i_generic::cur_dtype_, and utilities::D_SENTRY.
Referenced by utilities::Wrapper_i_generic::add_float_data(), utilities::Wrapper_i_generic::add_int_data(), and utilities::Wrapper_i_generic::close_frame().
bool Wrapper_i_generic::close_frame ()
Closes frame.
Throws error if not enough data was added
References utilities::Wrapper_i_generic::clear_data_type(), utilities::Wrapper_i_generic::cur_frame_size_, utilities::Wrapper_i_generic::frame_added_datatypes_, and utilities::Wrapper_i_generic::frame_open_.
Referenced by utilities::Wrapper_i_generic::open_frame(), and utilities::Wrapper_i_jb_binary::proc_file().
bool Wrapper_i_generic::finalize_wrapper ()
Closes wrapper from taking any new data.
Referenced by utilities::Wrapper_i_jb_binary::proc_file().
bool Wrapper_i_generic::open_frame (unsigned int frame, int N, float z)
Opens a frame to add data to it.
Parameters
frame the index of the frame
N the number of particles in the frame
Returns
if it works
References utilities::Wrapper_i_generic::close_frame(), utilities::Wrapper_i_generic::cur_frame_number_, utilities::Wrapper_i_generic::cur_frame_size_, utilities::Wrapper_i_generic::d_mapf_, utilities::Wrapper_i_generic::d_mapi_, utilities::Wrapper_i_generic::data_f_, utilities::Wrapper_i_generic::data_i_, utilities::Wrapper_i_generic::data_types_set_, utilities::Wrapper_i_generic::frame_added_datatypes_, utilities::Wrapper_i_generic::frame_c_, utilities::Wrapper_i_generic::frame_count_, utilities::Wrapper_i_generic::frame_open_, utilities::Wrapper_i_generic::frame_zdata_, utilities::Wrapper_i_generic::total_part_count_, utilities::V_BOOL, utilities::V_COMPLEX, utilities::V_ERROR, utilities::V_FLOAT, utilities::V_GUID, utilities::V_INT, utilities::V_STRING, utilities::V_TIME, utilities::v_type(), utilities::V_UINT, and utilities::VT2str_s().
Referenced by utilities::Wrapper_i_jb_binary::proc_file().
bool Wrapper_i_generic::open_wrapper ()
open wrapper to accept data, nukes everything currently in the wrapper
References utilities::Wrapper_i_generic::clean_data().
Referenced by utilities::Wrapper_i_jb_binary::proc_file().
bool Wrapper_i_generic::set_data_type (utilities::D_TYPE d_type)
Configures the object to take data of the given type.
Returns
if it works
References utilities::Wrapper_i_generic::cur_dtype_, utilities::D_SENTRY, utilities::Wrapper_i_generic::frame_added_datatypes_, and utilities::Wrapper_i_generic::frame_open_.
Referenced by utilities::Wrapper_i_jb_binary::proc_file().
bool utilities::Wrapper_i_generic::set_meta_data (const Md_store & md_store)
Sets frame meta-data for the frame.
bool Wrapper_i_generic::setup (const std::set< D_TYPE > & dtypes, int N, const Tuplef & dim)
Sets the number of frames to expect.
if this is not set will grow dynamically.
References utilities::Wrapper_i_generic::d_mapc_, utilities::Wrapper_i_generic::d_mapf_, utilities::Wrapper_i_generic::d_mapi_, utilities::Wrapper_i_generic::data_c_, utilities::Wrapper_i_generic::data_f_, utilities::Wrapper_i_generic::data_i_, utilities::Wrapper_i_generic::data_types_set_, utilities::Wrapper_i_generic::frame_c_, utilities::Wrapper_i_generic::frame_count_, utilities::Wrapper_i_generic::frame_zdata_, utilities::Wrapper_i_generic::locked_, utilities::Wrapper_i_generic::set_dims(), utilities::Data_map::set_lookup(), utilities::V_BOOL, utilities::V_COMPLEX, utilities::V_ERROR, utilities::V_FLOAT, utilities::V_GUID, utilities::V_INT, utilities::V_STRING, utilities::V_TIME, utilities::v_type(), utilities::V_UINT, and utilities::VT2str_s().
Referenced by utilities::Wrapper_i_jb_binary::proc_file().