Particle Identification and Tracking: iden/testing/im_series_test.cpp File Reference
im_series_test.cpp File Reference
#include <string>
#include <iostream>
#include "image_series.h"
#include "mm_md_parser.h"
#include "md_parser_dummy.h"
#include "md_store.h"
#include "image_stack.h"
Functions
int main ()
Variables
static string fname = "/home/tcaswell/colloids/2010/data/polyNIPAM_batch_12/20100524/4/exp2/28-8_warming_slow.tif"
static string fname2 = "/home/tcaswell/william_colloids/data/2010_05_24_coni1_2_cono1_4pass.tif"
static string base_name = "/home/tcaswell/colloids/2010/data/polyNIPAM_batch_12/2010-10-03/ssd_test/t3/test3_"
Function Documentation
int main ()
References base_name, fname, fname2, iden::Image_stack::get_frame_count(), iden::Image_series::get_frame_count(), iden::Image_stack::get_plane_md(), iden::Image_series::get_plane_md(), iden::Image_series::init(), iden::Image_stack::initialize(), utilities::Md_store::print(), iden::Image_stack::select_plane(), and iden::Image_series::select_plane().
Variable Documentation
string base_name = "/home/tcaswell/colloids/2010/data/polyNIPAM_batch_12/2010-10-03/ssd_test/t3/test3_" static
Referenced by main(), tracking::Accum_chi4_self::out_to_wrapper(), tracking::TA_vanHove::output_to_wrapper(), tracking::TA_disp::output_to_wrapper(), and tracking::TA_theta_rlim::output_to_wrapper().
string fname = "/home/tcaswell/colloids/2010/data/polyNIPAM_batch_12/20100524/4/exp2/28-8_warming_slow.tif" static
Referenced by main().
string fname2 = "/home/tcaswell/william_colloids/data/2010_05_24_coni1_2_cono1_4pass.tif" static
Referenced by main().