Particle Identification and Tracking: apps/link3D.cpp File Reference
link3D.cpp File Reference
#include <iostream>
#include "master_box_t.h"
#include "particle_base.h"
#include "hash_case.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "generic_wrapper_hdf.h"
#include "corr_gofr.h"
#include "track_shelf.h"
#include <unistd.h>
#include <vector>
#include "read_config.h"
#include <stdexcept>
Functions
int main (int argc, char *argv[])
Variables
static const string APP_NAME = "link3D :: "
Function Documentation
int main (int argc, char * argv[])
References APP_NAME, utilities::Read_config::contains_key(), utilities::D_DX, utilities::D_DY, utilities::D_E, utilities::D_I, utilities::D_R2, utilities::D_XPOS, utilities::D_YPOS, utilities::D_ZPOS, utilities::extract_prams(), utilities::Read_config::get_store(), tracking::Track_shelf::get_track_count(), utilities::Read_config::get_value(), tracking::hash_case::init(), tracking::Master_box::init(), utilities::Filter_ers::init(), tracking::hash_case::link(), tracking::Track_shelf::output_link_to_wrapper(), tracking::Track_shelf::remove_short_tracks(), and tracking::Track_shelf::split_to_parts().
Variable Documentation
const string APP_NAME = "link3D :: " static
Referenced by main().