Particle Identification and Tracking: testing/make_fake_hdf.cpp File Reference
make_fake_hdf.cpp File Reference
#include <iostream>
#include <stdexcept>
#include <sstream>
#include <string>
#include <vector>
#include <map>
#include <cmath>
#include "master_box_t.h"
#include "particle_base.h"
#include "hash_case.h"
#include "wrapper_o_hdf.h"
#include "filter.h"
#include "wrapper_i.h"
#include "part_def.h"
#include "md_store.h"
Classes
class utilities::Wrapper_i_dummy
Wrapper class for testing purposes.
Namespaces
utilities
Namespace for utilities and helper functions.
Constant Groups
utilities
Namespace for utilities and helper functions.
Functions
template<class T >
std::string to_string (const T &t)
int main (int argc, const char *argv[])
Function Documentation
int main (int argc, const char * argv[])
References utilities::Md_store::add_element(), utilities::Wrapper_o_hdf::add_meta_data(), utilities::D_XPOS, utilities::D_YPOS, utilities::Wrapper_o_hdf::finalize_wrapper(), fname, tracking::hash_case::init(), tracking::Master_box::init(), utilities::Wrapper_o_hdf::initialize_wrapper(), tracking::hash_case::output_to_wrapper(), utilities::Wrapper_in::set_Md_store(), utilities::Wrapper_in::set_Md_store_size(), tracking::Master_box::size(), and to_string().
template<class T > std::string to_string (const T & t) inline