Particle Identification and Tracking: testing/md_store_test.cpp File Reference
md_store_test.cpp File Reference
#include "md_store.h"
#include <iostream>
#include <string>
Functions
template<class T >
bool test_fun (string str, T val, Md_store &md)
int main ()
Function Documentation
int main ()
References utilities::Md_store::add_elements(), and test_fun().
template<class T > bool test_fun (string str, T val, Md_store & md)
References utilities::Md_store::get_value(), and utilities::Md_store::set_value().
Referenced by main().