Particle Identification and Tracking: iden/testing/mm_md_test.cpp File Reference
mm_md_test.cpp File Reference
#include <iostream>
#include <stdexcept>
#include <string>
#include "FreeImagePlus.h"
#include "mm_md_parser.h"
#include "md_store.h"
#include "enum_utils.h"
Functions
int main ()
Variables
static string fname = "/home/tcaswell/colloids/data/polyNIPAM_batch_12/20100524/4/exp2/27-7_27-1_27-6_vslow.tif"
Function Documentation
int main ()
References fname, utilities::Md_store::get_key(), utilities::Md_store::get_key_index(), utilities::Md_store::get_type(), utilities::Md_store::get_val(), utilities::Md_store::get_value(), iden::Mm_md_parser::parse_md(), utilities::Md_store::size(), and utilities::VT2str_s().
Variable Documentation
string fname = "/home/tcaswell/colloids/data/polyNIPAM_batch_12/20100524/4/exp2/27-7_27-1_27-6_vslow.tif" static
Referenced by main().