Particle Identification and Tracking: iden/cxx/mm_md_parser.cpp File Reference
mm_md_parser.cpp File Reference
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <vector>
#include <xercesc/dom/DOM.hpp>
#include <xercesc/dom/DOMDocument.hpp>
#include <xercesc/dom/DOMDocumentType.hpp>
#include <xercesc/dom/DOMElement.hpp>
#include <xercesc/dom/DOMImplementation.hpp>
#include <xercesc/dom/DOMImplementationLS.hpp>
#include <xercesc/dom/DOMNodeIterator.hpp>
#include <xercesc/dom/DOMNodeList.hpp>
#include <xercesc/dom/DOMText.hpp>
#include <xercesc/framework/MemBufInputSource.hpp>
#include <xercesc/parsers/XercesDOMParser.hpp>
#include <xercesc/util/XMLUni.hpp>
#include "mm_md_parser.h"
#include "FreeImagePlus.h"
#include "md_store.h"
Functions
void parse_description (string &des, Md_store *store)
std::string de_mangle_mmdate (const std::string &in)
Local function to slightly re-format the time string from metamorph.
Variables
static const char * gMemBufId = "ImageDescription"
Function Documentation
std::string de_mangle_mmdate (const std::string & in)
Local function to slightly re-format the time string from metamorph.
Referenced by iden::Mm_md_parser::parse_elements().
void parse_description (string & des, Md_store * store)
References utilities::Md_store::add_element().
Referenced by iden::Mm_md_parser::parse_elements(), and parse_elements().
Variable Documentation
const char* gMemBufId = "ImageDescription" static
Referenced by iden::Mm_md_parser::parse_md().