Particle Identification and Tracking: utilities Namespace Reference
utilities Namespace Reference
Namespace for utilities and helper functions.
Classes
class Accum_case
A class to hold a stack of accum objects for handing into a hash_case.
class Attr_list_hdf
Wraps the attribute functionality of hdf objects.
class CL_parse
A class to wrap the parsing of the command line to extract the input file, output file and parameter file.
class Counted_vector
A class for computing many averages in parallel.
class Data_map
class to handle translation from D_TYPE to column position for flat data structures.
struct Data_store
A struct to hold the data_map and raw data for input and output wrappers.
class Ll_range_error
Exception class derived from the standard range_error class to indicate when a linked list has stepped over it's range.
class Null_field
Exception to report when a function that should return valid pointer from an object, but the field is NULL in the object.
class Filter
ABC for filter objects.
class Filter_trivial
a trivial filter class that does nothing
class Filter_ers
A basic filter, does rg (top), shift (top) and eccentricity (top) cuts.
class Filter_ersI
A basic filter, does rg (top), shift (top), eccentricity (top), and I (bottom) cuts.
class Generic_wrapper
An interface for extracting data from the internal data structures.
class Generic_wrapper_read
Abstract base class to provide an interface for reading data out of Generic_wrapper objects.
class Generic_wrapper_hdf
generic_wrapper for writing to hdf files
class Histogram
Base class for historgram objects.
class Histogram2D
Implements a 2D histogram.
class Md_store
A class to hold meta data.
class ND_Array
A N-D array.
class Read_config
class for reading configuration from xml files.
class SQL_handler
Class to wrap around the sqlite3 interface to deal with making connections to data basese, cleaning up after them etc.
class Tuple
Class for carrying around the posistion and velocity vectors.
class Wrapper_in
A mostly abstract base class for input wrappers.
class Wrapper_i_dummy
Wrapper class for testing purposes.
class Wrapper_i_file
Wrapper class for dealing with data from a text file.
class Wrapper_i_generic
Wrapper class for eating data from arbitrary sources.
class Wrapper_i_hdf
Wrapper class for eating data from hdf files, take 2.
class Wrapper_i_jb_binary
Wrapper class for dealing with data from Justin's simulations.
class Wrapper_out
ABC for output wrappers.
class wrapper_o_file
wrapper_o class for dealing with writing data to a file.
class Wrapper_o_hdf
Wrapper class for dealing with output to matlab.
class Wrapper_o_hdf_group
Wrapper class for dealing with output to matlab.
Typedefs
typedef enum utilities::W_TYPE W_TYPE
Enumeration for wrapper types.
typedef enum utilities::D_TYPE D_TYPE
Enumeration for data types (where type is the physical meaning of the data).
typedef enum utilities::V_TYPE V_TYPE
Enumeration for the type of value the data is (ie float, int,complex)
typedef enum utilities::FILT_TYPE FILT_TYPE
Enumeration for keeping track of which filter type a filter is, useful for checking to make sure that the factory behaved properly.
typedef Tuple< int, 2 > Tuplei
typedef Tuple< float, 2 > Tuplef
typedef enum utilities::F_TYPE F_TYPE
Enumeration for functions that maps to the tables in the database.
Enumerations
enum W_TYPE { W_MATLAB = 0, W_TEXT, W_NING, W_HDF }
Enumeration for wrapper types.
enum D_TYPE {
D_INDEX =0, D_XPOS =1, D_YPOS =2, D_FRAME =3,
D_I =4, D_R2 =5, D_E =6, D_NEXT_INDX =7,
D_PREV_INDX =8, D_DX =9, D_DY =10, D_ORGX =11,
D_ORGY =12, D_ZPOS =13, D_TRACKID =14, D_S_ORDER_PARAMETER =15,
D_MULT =16, D_N_SIZE =17, D_SENTRY
}
Enumeration for data types (where type is the physical meaning of the data).
enum V_TYPE {
V_ERROR = -1, V_UINT = 0, V_INT =1, V_FLOAT =2,
V_COMPLEX =3, V_STRING =4, V_BOOL =5, V_TIME =6,
V_GUID =7
}
Enumeration for the type of value the data is (ie float, int,complex)
enum FILT_TYPE { FILT_TRIV = 0, FILT_ERS, FILT_ERSImin }
Enumeration for keeping track of which filter type a filter is, useful for checking to make sure that the factory behaved properly.
enum F_TYPE {
F_NOFUNCTION = 0, F_IDEN = 1, F_IDEN_AVG = 2, F_GOFR = 3,
F_GOFR3D = 4, F_GOFR_BY_PLANE = 5, F_LINK3D = 6, F_MSD = 7,
F_PHI6 = 8, F_TRACK_STATS = 9, F_TRACKING = 10, F_VANHOVE = 11,
F_MSD_SWEEP = 12
}
Enumeration for functions that maps to the tables in the database.
Functions
std::string DT2str_s (D_TYPE in)
Helper functions to convert D_TYPEs in to short name strings.
D_TYPE str2DT_s (std::string in)
Helper functions to convert short name strings in to D_TYPEs.
V_TYPE v_type (D_TYPE in)
Helper function to map between D_TYPE and V_TYPE.
std::string format_dset_name (D_TYPE type, int comp_num)
Helper function to format dset names with computation numbers attached.
std::string format_name (const std::string &name,int comp_num)
Helper function to format computation numbers on to strings.
V_TYPE str2VT_s (const std::string &type_str)
Helper function to make string in to V_TYPE.
V_TYPE str2VT_s (const char *const in)
Helper function to make string in to V_TYPE.
std::string VT2str_s (V_TYPE)
Helper function to make v_types to strings.
template<typename _CharT , class _Traits >
std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const Data_map &in)
prints out the data_map to cout lifted almost whole cloth from c++/4.3/complex
Filter * filter_factory (const Md_store &filter_prams)
Guesses which filter to generate from the parameters it is given in the Md_store object.
Md_store extract_prams (const std::string &fname, int comp_num, const std::vector< std::string > &pram_list)
Extracts filter parameters from a data file.
std::string ftype_to_str (F_TYPE f)
template<typename _CharT , class _Traits , class T , int length>
std::basic_ostream< _CharT,
_Traits > & operator<< (std::basic_ostream< _CharT, _Traits > &__os, const Tuple< T, length > &in)
prints out the tuple to cout lifted almost whole cloth from c++/4.3/complex
Variables
const int format_padding_ = 7
Detailed Description
Namespace for utilities and helper functions.
Typedef Documentation
typedef enum utilities::D_TYPE utilities::D_TYPE
Enumeration for data types (where type is the physical meaning of the data).
If you add to this you MUST update the count below this, add the D_TYPE to the V_TYPE conversion function, and D2Str function.
typedef enum utilities::F_TYPE utilities::F_TYPE
Enumeration for functions that maps to the tables in the database.
The values of the enumeration need to stay synced with the values of func_names table in the database. This should be replaced with something more flexible eventually.
typedef enum utilities::FILT_TYPE utilities::FILT_TYPE
Enumeration for keeping track of which filter type a filter is, useful for checking to make sure that the factory behaved properly.
typedef Tuple<float,2> utilities::Tuplef
typedef Tuple<int,2> utilities::Tuplei
typedef enum utilities::V_TYPE utilities::V_TYPE
Enumeration for the type of value the data is (ie float, int,complex)
typedef enum utilities::W_TYPE utilities::W_TYPE
Enumeration for wrapper types.
I do not think that this is used by anything
Todo:
remove this
Enumeration Type Documentation
enum utilities::D_TYPE
Enumeration for data types (where type is the physical meaning of the data).
If you add to this you MUST update the count below this, add the D_TYPE to the V_TYPE conversion function, and D2Str function.
Enumerator
D_INDEX
D_XPOS
D_YPOS
D_FRAME
D_I
D_R2
D_E
D_NEXT_INDX
D_PREV_INDX
D_DX
D_DY
D_ORGX
D_ORGY
D_ZPOS
D_TRACKID
D_S_ORDER_PARAMETER
D_MULT
D_N_SIZE
D_SENTRY
enum utilities::F_TYPE
Enumeration for functions that maps to the tables in the database.
The values of the enumeration need to stay synced with the values of func_names table in the database. This should be replaced with something more flexible eventually.
Enumerator
F_NOFUNCTION
F_IDEN
F_IDEN_AVG
F_GOFR
F_GOFR3D
F_GOFR_BY_PLANE
F_LINK3D
F_MSD
F_PHI6
F_TRACK_STATS
F_TRACKING
F_VANHOVE
F_MSD_SWEEP
enum utilities::FILT_TYPE
Enumeration for keeping track of which filter type a filter is, useful for checking to make sure that the factory behaved properly.
Enumerator
FILT_TRIV
FILT_ERS
FILT_ERSImin
enum utilities::V_TYPE
Enumeration for the type of value the data is (ie float, int,complex)
Enumerator
V_ERROR
V_UINT
V_INT
V_FLOAT
V_COMPLEX
V_STRING
V_BOOL
V_TIME
V_GUID
enum utilities::W_TYPE
Enumeration for wrapper types.
I do not think that this is used by anything
Todo:
remove this
Enumerator
W_MATLAB
W_TEXT
W_NING
W_HDF
Function Documentation
std::string utilities::DT2str_s (D_TYPE in)
Helper functions to convert D_TYPEs in to short name strings.
References D_DX, D_DY, D_E, D_FRAME, D_I, D_INDEX, D_MULT, D_N_SIZE, D_NEXT_INDX, D_ORGX, D_ORGY, D_PREV_INDX, D_R2, D_S_ORDER_PARAMETER, D_TRACKID, D_XPOS, D_YPOS, and D_ZPOS.
Referenced by format_dset_name(), utilities::Wrapper_i_hdf::get_value(), and utilities::Wrapper_i_generic::get_value().
Md_store utilities::extract_prams (const std::string & fname, int comp_num, const std::vector< std::string > & pram_list)
Extracts filter parameters from a data file.
Extracts the parameters asked for. This functionality should be folded into the wrapper class.
References utilities::Md_store::add_element(), utilities::Attr_list_hdf::contains_attr(), D_XPOS, format_dset_name(), utilities::Attr_list_hdf::get_type(), utilities::Attr_list_hdf::get_value(), V_BOOL, V_COMPLEX, V_ERROR, V_FLOAT, V_GUID, V_INT, V_STRING, V_TIME, V_UINT, and VT2str_s().
Referenced by main().
Filter * utilities::filter_factory (const Md_store & filter_prams)
Guesses which filter to generate from the parameters it is given in the Md_store object.
The returned object needs to be cleaned up.
References utilities::Md_store::contains_key(), utilities::Filter_ers::init(), and utilities::Filter_ersI::init().
Referenced by main().
std::string utilities::format_dset_name (D_TYPE type, int comp_num)
Helper function to format dset names with computation numbers attached.
References DT2str_s(), and format_name().
Referenced by extract_prams(), utilities::Wrapper_o_hdf::initialize_wrapper(), local_add_meta(), utilities::Wrapper_i_hdf::priv_init(), and utilities::Wrapper_o_hdf_group::Wrapper_o_hdf_group().
std::string utilities::format_name (const std::string & name, int comp_num)
Helper function to format computation numbers on to strings.
References format_padding_.
Referenced by utilities::Wrapper_o_hdf::add_meta_data_comp(), format_dset_name(), main(), tracking::Accum_chi4_self::out_to_wrapper(), tracking::Corr_pair_diffusion::out_to_wrapper(), tracking::Corr_case::out_to_wrapper(), tracking::TA_vanHove::output_to_wrapper(), tracking::TA_disp::output_to_wrapper(), tracking::TA_theta_rlim::output_to_wrapper(), tracking::TA_msd::output_to_wrapper(), and tracking::Track_shelf::output_to_wrapper().
std::string utilities::ftype_to_str (F_TYPE f)
References F_GOFR, F_GOFR3D, F_GOFR_BY_PLANE, F_IDEN, F_IDEN_AVG, F_LINK3D, F_MSD, F_MSD_SWEEP, F_NOFUNCTION, F_PHI6, F_TRACK_STATS, F_TRACKING, and F_VANHOVE.
template<typename _CharT , class _Traits > std::basic_ostream<_CharT, _Traits>& utilities::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const Data_map & in)
prints out the data_map to cout lifted almost whole cloth from c++/4.3/complex
References D_SENTRY.
template<typename _CharT , class _Traits , class T , int length> std::basic_ostream<_CharT, _Traits>& utilities::operator<< (std::basic_ostream< _CharT, _Traits > & __os, const Tuple< T, length > & in)
prints out the tuple to cout lifted almost whole cloth from c++/4.3/complex
D_TYPE utilities::str2DT_s (std::string in)
Helper functions to convert short name strings in to D_TYPEs.
References D_TRACKID.
V_TYPE utilities::str2VT_s (const std::string & type_str)
Helper function to make string in to V_TYPE.
References V_BOOL, V_ERROR, V_FLOAT, V_GUID, V_INT, V_STRING, V_TIME, and V_UINT.
Referenced by utilities::Md_store::add_element(), and str2VT_s().
V_TYPE utilities::str2VT_s (const char *const in)
Helper function to make string in to V_TYPE.
References str2VT_s().
V_TYPE utilities::v_type (D_TYPE in)
Helper function to map between D_TYPE and V_TYPE.
References D_DX, D_DY, D_E, D_FRAME, D_I, D_INDEX, D_MULT, D_N_SIZE, D_NEXT_INDX, D_ORGX, D_ORGY, D_PREV_INDX, D_R2, D_S_ORDER_PARAMETER, D_TRACKID, D_XPOS, D_YPOS, D_ZPOS, V_COMPLEX, V_ERROR, V_FLOAT, and V_INT.
Referenced by utilities::Wrapper_i_generic::add_float_data(), utilities::Wrapper_i_generic::add_int_data(), tracking::particle_base::get_value(), utilities::Wrapper_i_hdf::get_value(), utilities::Wrapper_i_generic::get_value(), tracking::particle_track::get_value(), utilities::Wrapper_i_generic::open_frame(), utilities::Wrapper_i_hdf::priv_init(), utilities::Wrapper_i_generic::setup(), utilities::Wrapper_o_hdf_group::store_particle(), utilities::Wrapper_o_hdf_group::Wrapper_o_hdf_group(), and utilities::Wrapper_o_hdf_group::write_to_disk().
std::string utilities::VT2str_s (V_TYPE type)
Helper function to make v_types to strings.
References V_BOOL, V_COMPLEX, V_ERROR, V_FLOAT, V_GUID, V_INT, V_STRING, V_TIME, and V_UINT.
Referenced by utilities::Wrapper_o_hdf::add_meta_data_list(), extract_prams(), utilities::Md_store::get_value(), main(), utilities::Wrapper_i_generic::open_frame(), utilities::Md_store::print(), utilities::Wrapper_i_hdf::priv_init(), utilities::Wrapper_i_generic::setup(), utilities::Wrapper_o_hdf_group::store_particle(), and utilities::Wrapper_o_hdf_group::Wrapper_o_hdf_group().
Variable Documentation
const int utilities::format_padding_ = 7
Referenced by format_name().