Particle Identification and Tracking: iden Namespace Reference
iden Namespace Reference
Name space for all of the particle identification code.
Classes
class Filestreams
class Iden
Class to encapsulate all of the image processing for particle identification.
class Image2D
class Image_base
This is an ABC for different file layouts, ie to make dealing with multi-part files and the spew that comes out of stream to disk easy to change between.
class Image_series
class Image_stack
class Tophat_Kernel
class Gaussian_Kernel
class Dilation_Kernel
class Convolution_Kernel
class MD_parser
A base class for parsers that extract meta data from image files.
class MD_parser_dummy
A class that returns an empty Md_store object as a stand in for a proper parser.
class Mm_md_parser
A class for parsing and extracting the meta data from the tiff directories of tif files generated by metamorph.
class Wrapper_i_plu
Wrapper class for dealing with data from Peter Lu's code.
Typedefs
typedef enum iden::PIX_TYPE PIX_TYPE
Enumeration of pixel sizes.
typedef enum iden::MD_TYPE MD_TYPE
Enumeration of Meta data format types.
Enumerations
enum PIX_TYPE {
U16 =0, U8, S16, F32,
ERROR
}
Enumeration of pixel sizes.
enum MD_TYPE { NONE =0, MM }
Enumeration of Meta data format types.
Functions
IppStatus BandPass_2D (Image2D &image_in, Image2D &image_bpass, const int feature_radius, const float hwhm_length)
void RecenterImage (Image2D &image)
IppStatus FindLocalMax_2D (Image2D &image_bpass, Image2D &image_bpass_thresh, Image2D &image_subtracted, const float threshold, const int dilation_radius)
void PrintParticleDataHeader (std::ostream &out)
void PrintParticleData (std::ostream &out, const Ipp32f particledata[][9], const int startrow, const int endrow, const int framenumber, const int stacknumber)
Ipp32f(* ParticleStatistics (Image2D &image_localmax, Image2D &image_in, const int mask_radius, const int feature_radius, int &counter))[9]
std::string format_name (const std::string &dirname, const std::string &basename, int padding, unsigned int plane)
void Print2DKernel8u (const int diameter, const Ipp8u *kernel)
void Print2DKernel32f (const int diameter, const Ipp32f *kernel)
Detailed Description
Name space for all of the particle identification code.
Typedef Documentation
typedef enum iden::MD_TYPE iden::MD_TYPE
Enumeration of Meta data format types.
typedef enum iden::PIX_TYPE iden::PIX_TYPE
Enumeration of pixel sizes.
Enumeration Type Documentation
enum iden::MD_TYPE
Enumeration of Meta data format types.
Enumerator
NONE
MM
enum iden::PIX_TYPE
Enumeration of pixel sizes.
Enumerator
U16
U8
S16
F32
ERROR
Function Documentation
IppStatus iden::BandPass_2D (Image2D & image_in, Image2D & image_bpass, const int feature_radius, const float hwhm_length)
References iden::Image2D::get_height(), iden::Image2D::get_image2D(), iden::Image2D::get_stepsize(), and iden::Image2D::get_width().
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), and iden::Iden::process_frame().
IppStatus iden::FindLocalMax_2D (Image2D & image_bpass, Image2D & image_bpass_thresh, Image2D & image_subtracted, const float threshold, const int dilation_radius)
References epsilon, iden::Image2D::get_height(), iden::Image2D::get_image2D(), iden::Image2D::get_ROIfull(), iden::Image2D::get_stepsize(), iden::Image2D::get_width(), and RecenterImage().
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), and iden::Iden::process_frame().
std::string iden::format_name (const std::string & dirname, const std::string & basename, int padding, unsigned int plane)
Referenced by iden::Image_series::select_plane().
Ipp32f(* iden::ParticleStatistics (Image2D & image_localmax, Image2D & image_in, const int mask_radius, const int feature_radius, int & counter))[9]
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), and iden::Iden::process_frame().
void iden::Print2DKernel32f (const int diameter, const Ipp32f * kernel)
void iden::Print2DKernel8u (const int diameter, const Ipp8u * kernel)
void iden::PrintParticleData (std::ostream & out, const Ipp32f particledata[][9], const int startrow, const int endrow, const int framenumber, const int stacknumber)
void iden::PrintParticleDataHeader (std::ostream & out)
void iden::RecenterImage (Image2D & image)
References iden::Image2D::get_image2D(), iden::Image2D::get_ROIfull(), and iden::Image2D::get_stepsize().
Referenced by iden::Iden::fill_wrapper(), iden::Iden::fill_wrapper_avg(), FindLocalMax_2D(), and iden::Iden::process_frame().