Particle Identification and Tracking: apps/phi6.cpp File Reference
phi6.cpp File Reference
#include <iostream>
#include <map>
#include <vector>
#include <stdexcept>
#include "particle_base.h"
#include "hash_case.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "hash_shelf.h"
#include "generic_wrapper_hdf.h"
#include "corr_gofr.h"
#include "read_config.h"
#include "cl_parse.h"
#include "sql_handler.h"
#include "md_store.h"
Functions
int main (int argc, char *argv[])
Variables
static const string APP_NAME = "phi6"
Function Documentation
int main (int argc, char * argv[])
References utilities::Md_store::add_element(), utilities::Md_store::add_elements(), utilities::SQL_handler::add_mdata(), utilities::Wrapper_o_hdf::add_meta_data_list(), APP_NAME, utilities::SQL_handler::close_connection(), utilities::SQL_handler::commit(), utilities::Read_config::contains_key(), utilities::D_DX, utilities::D_DY, utilities::D_E, utilities::D_N_SIZE, utilities::D_R2, utilities::D_S_ORDER_PARAMETER, utilities::D_XPOS, utilities::D_YPOS, utilities::extract_prams(), utilities::F_PHI6, utilities::Wrapper_o_hdf::finalize_wrapper(), utilities::CL_parse::get_fpram(), utilities::Filter_ers::get_parameters(), utilities::Read_config::get_store(), utilities::Read_config::get_value(), tracking::hash_case::init(), utilities::Filter_ers::init(), utilities::Wrapper_o_hdf::initialize_wrapper(), utilities::SQL_handler::open_connection(), tracking::hash_case::output_to_wrapper(), utilities::CL_parse::parse(), tracking::hash_case::pass_fun_to_part(), tracking::hash_case::pass_fun_to_shelf(), and utilities::SQL_handler::start_comp().
Variable Documentation
const string APP_NAME = "phi6" static
Referenced by main().