Particle Identification and Tracking: iden/apps/process.cpp File Reference
process.cpp File Reference
#include <iostream>
#include <stdexcept>
#include <getopt.h>
#include "part_def.h"
#include "wrapper_i_plu.h"
#include "iden.h"
#include "master_box_t.h"
#include "particle_base.h"
#include "hash_case.h"
#include "tuple.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "attr_list_hdf.h"
#include "read_config.h"
#include "image_stack.h"
#include "image_series.h"
#include "mm_md_parser.h"
#include "md_parser_dummy.h"
#include "H5Cpp.h"
Functions
int main (int argc, char *const argv[])
Function Documentation
int main (int argc, char *const argv[])
References utilities::Wrapper_o_hdf::add_meta_data_list(), base_name, utilities::Read_config::contains_key(), utilities::Wrapper_o_hdf::finalize_wrapper(), iden::Wrapper_i_plu::get_data_types(), iden::Wrapper_i_plu::get_dims(), iden::Wrapper_i_plu::get_num_entries(), iden::Wrapper_i_plu::get_num_frames(), utilities::Read_config::get_store(), utilities::Read_config::get_value(), iden::Image_series::init(), tracking::hash_case::init(), tracking::Master_box::init(), iden::Image_stack::initialize(), utilities::Wrapper_o_hdf::initialize_wrapper(), iden::MM, iden::NONE, tracking::hash_case::output_to_wrapper(), iden::Iden::set_image_src(), and tracking::Master_box::size().