Particle Identification and Tracking: testing/rtt_hc.cpp File Reference
rtt_hc.cpp File Reference
#include <string>
#include <iostream>
#include <ctime>
#include "hash_case.h"
#include "track_shelf.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "generic_wrapper_hdf.h"
#include "read_config.h"
#include "cl_parse.h"
#include "md_store.h"
Functions
int main (int argc, char *const argv[])
Variables
static string APP_NAME = "rtt_hc :: "
Function Documentation
int main (int argc, char *const argv[])
References utilities::D_NEXT_INDX, utilities::D_PREV_INDX, utilities::D_TRACKID, utilities::D_XPOS, utilities::D_YPOS, utilities::CL_parse::get_fin(), utilities::CL_parse::get_fout(), utilities::CL_parse::get_fpram(), utilities::Read_config::get_value(), tracking::hash_case::init(), utilities::Wrapper_i_hdf::initialize(), and utilities::CL_parse::parse().
Variable Documentation
string APP_NAME = "rtt_hc :: " static