Particle Identification and Tracking: apps/sofq.cpp File Reference
sofq.cpp File Reference
#include "accum_sofq.h"
#include <set>
#include "enum_utils.h"
#include "wrapper_i.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "master_box_t.h"
#include "hash_case.h"
#include "read_config.h"
Functions
int main (int argc, char *argv[])
Variables
static string APP_NAME = "sofq :: "
Function Documentation
int main (int argc, char * argv[])
References APP_NAME, tracking::Master_box::compute_accum(), utilities::Read_config::contains_key(), utilities::D_DX, utilities::D_DY, utilities::D_E, utilities::D_R2, utilities::D_XPOS, utilities::D_YPOS, tracking::Accum_sofq::display(), utilities::Read_config::get_value(), tracking::Master_box::init(), and tracking::Master_box::size().
Variable Documentation
string APP_NAME = "sofq :: " static
Referenced by main().