Particle Identification and Tracking: testing/sofq_test.cpp File Reference
sofq_test.cpp File Reference
#include "accum_sofq.h"
#include <set>
#include "enum_utils.h"
#include "wrapper_i.h"
#include "filter.h"
#include "master_box_t.h"
#include "hash_case.h"
#include <cstdlib>
#include "particle_base.h"
Classes
class utilities::Wrapper_i_dummy
Wrapper class for testing purposes.
Namespaces
utilities
Namespace for utilities and helper functions.
Constant Groups
utilities
Namespace for utilities and helper functions.
Functions
int main ()
Function Documentation
int main ()
References tracking::Master_box::compute_accum(), utilities::D_XPOS, utilities::D_YPOS, tracking::Accum_sofq::display(), tracking::Master_box::init(), and tracking::Master_box::size().