Particle Identification and Tracking: testing/sql_test.cpp File Reference
sql_test.cpp File Reference
#include "sql_handler.h"
#include "md_store.h"
#include <string>
#include <iostream>
Functions
int test_fun (Md_store &md_store, utilities::F_TYPE f_type, string t_name, SQL_handler &test)
int main ()
Function Documentation
int main ()
References utilities::Md_store::add_element(), utilities::SQL_handler::add_mdata(), utilities::SQL_handler::close_connection(), utilities::SQL_handler::commit(), utilities::F_IDEN, utilities::F_MSD, utilities::F_TRACKING, utilities::SQL_handler::get_comp_mdata(), utilities::SQL_handler::make_test_db(), utilities::Md_store::print(), utilities::SQL_handler::start_comp(), and test_fun().
int test_fun (Md_store & md_store, utilities::F_TYPE f_type, string t_name, SQL_handler & test)
References utilities::Md_store::add_element(), utilities::SQL_handler::add_mdata(), utilities::SQL_handler::commit(), utilities::SQL_handler::get_comp_mdata(), utilities::Md_store::print(), and utilities::SQL_handler::start_comp().