Particle Identification and Tracking: apps/tracking.cpp File Reference
tracking.cpp File Reference
#include "master_box_t.h"
#include "particle_base.h"
#include "hash_case.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "generic_wrapper_hdf.h"
#include <unistd.h>
#include <vector>
#include "read_config.h"
#include "cl_parse.h"
#include "md_store.h"
#include "track_shelf.h"
#include "sql_handler.h"
Functions
int main (int argc, char *const argv[])
Variables
static string APP_NAME = "tracking :: "
static float MAX_HASH_DIM = 500
Function Documentation
int main (int argc, char *const argv[])
References utilities::Md_store::add_element(), utilities::SQL_handler::add_mdata(), utilities::Wrapper_o_hdf::add_meta_data_list(), utilities::SQL_handler::close_connection(), utilities::SQL_handler::commit(), tracking::hash_case::compute_mean_disp(), utilities::Read_config::contains_key(), utilities::D_DX, utilities::D_DY, utilities::D_E, utilities::D_I, utilities::D_NEXT_INDX, utilities::D_PREV_INDX, utilities::D_R2, utilities::D_TRACKID, utilities::D_XPOS, utilities::D_YPOS, utilities::extract_prams(), utilities::F_TRACKING, utilities::filter_factory(), utilities::Wrapper_o_hdf::finalize_wrapper(), tracking::hash_case::get_avg_dtime(), tracking::hash_case::get_avg_temp(), utilities::Wrapper_i_hdf::get_dims(), utilities::CL_parse::get_fpram(), utilities::Wrapper_i_hdf::get_num_frames(), utilities::Read_config::get_store(), tracking::Track_shelf::get_track_count(), utilities::Read_config::get_value(), tracking::hash_case::init(), tracking::Master_box::init(), utilities::Wrapper_i_hdf::initialize(), utilities::Wrapper_o_hdf::initialize_wrapper(), tracking::hash_case::link(), utilities::Tuple< T, length >::max(), MAX_HASH_DIM, utilities::SQL_handler::open_connection(), tracking::hash_case::output_to_wrapper(), tracking::Track_shelf::output_to_wrapper(), utilities::CL_parse::parse(), tracking::Track_shelf::remove_short_tracks(), tracking::Track_shelf::renumber(), and utilities::SQL_handler::start_comp().
Variable Documentation
string APP_NAME = "tracking :: " static
float MAX_HASH_DIM = 500 static
Referenced by main().