Particle Identification and Tracking: testing/track_test.cpp File Reference
track_test.cpp File Reference
#include <iostream>
#include "master_box_t.h"
#include "particle_track.h"
#include "hash_case.h"
#include "wrapper_i_dummy.h"
#include "filter.h"
#include "corr_gofr.h"
#include "gnuplot_i.hpp"
#include "track_shelf.h"
#include "track_box.h"
Functions
int main (int argc, const char *argv[])
Function Documentation
int main (int argc, const char * argv[])
References utilities::D_DX, utilities::D_DY, utilities::D_E, utilities::D_I, utilities::D_MULT, utilities::D_R2, utilities::D_XPOS, utilities::D_YPOS, utilities::D_ZPOS, tracking::Master_box::get_particle(), tracking::Master_box::init(), tracking::Track_shelf::print(), tracking::Track_box::print(), tracking::Track_box::push_back(), tracking::Master_box::size(), and tracking::Track_box::split_to_parts().