Particle Identification and Tracking: apps/vanHove.cpp File Reference
vanHove.cpp File Reference
#include <string>
#include <iostream>
#include <ctime>
#include "track_shelf.h"
#include "hash_case.h"
#include "wrapper_o_hdf.h"
#include "wrapper_i_hdf.h"
#include "filter.h"
#include "generic_wrapper_hdf.h"
#include "master_box_t.h"
#include "read_config.h"
#include "cl_parse.h"
#include "md_store.h"
#include "ta_vanHove.h"
#include "sql_handler.h"
Functions
int main (int argc, char *const argv[])
Variables
static string APP_NAME = "vanHove :: "
Function Documentation
int main (int argc, char *const argv[])
References utilities::Md_store::add_element(), utilities::Md_store::add_elements(), utilities::SQL_handler::close_connection(), tracking::Track_shelf::compute_corrected_TA(), tracking::hash_case::compute_mean_disp(), utilities::D_NEXT_INDX, utilities::D_PREV_INDX, utilities::D_TRACKID, utilities::D_XPOS, utilities::D_YPOS, utilities::F_VANHOVE, tracking::hash_case::get_avg_dtime(), tracking::hash_case::get_avg_temp(), utilities::Wrapper_i_hdf::get_dims(), utilities::CL_parse::get_fpram(), utilities::Wrapper_i_hdf::get_num_frames(), utilities::Read_config::get_store(), utilities::Read_config::get_value(), tracking::hash_case::init(), tracking::Master_box::init(), tracking::Track_shelf::init(), utilities::Wrapper_i_hdf::initialize(), utilities::SQL_handler::open_connection(), tracking::TA_vanHove::output_to_wrapper(), utilities::CL_parse::parse(), tracking::Track_shelf::remove_short_tracks(), and utilities::SQL_handler::start_comp().
Variable Documentation
string APP_NAME = "vanHove :: " static