Particle Identification and Tracking: common_src/cxx/wrapper_o_hdf.cpp File Reference
wrapper_o_hdf.cpp File Reference
#include <iostream>
#include <sstream>
#include <stdexcept>
#include "particle_track.h"
#include "attr_list_hdf.h"
#include "read_config.h"
#include "track_box.h"
#include "wrapper_o_hdf.h"
#include "wrapper_o_hdf_group.h"
#include "H5Cpp.h"
Functions
template<class T >
void local_add_meta_data_root (const std::string &key, T val, bool wrapper_open, H5File *file)
template<class T >
void local_add_meta_data (const std::string &key, T val, bool group_open, Wrapper_o_hdf_group *current_group)
template<class T >
void local_add_meta (const std::string &key, T val, D_TYPE dset_type, bool wrapper_open, int comp_number, Group *dset_pram_group)
Function Documentation
template<class T > void local_add_meta (const std::string & key, T val, D_TYPE dset_type, bool wrapper_open, int comp_number, Group * dset_pram_group)
References utilities::format_dset_name(), and utilities::Attr_list_hdf::set_value().
Referenced by utilities::Wrapper_o_hdf::add_meta_data().
template<class T > void local_add_meta_data (const std::string & key, T val, bool group_open, Wrapper_o_hdf_group * current_group)
References utilities::Wrapper_o_hdf_group::set_meta_data().
Referenced by utilities::Wrapper_o_hdf::add_meta_data(), and utilities::Wrapper_o_hdf::add_meta_data_comp().
template<class T > void local_add_meta_data_root (const std::string & key, T val, bool wrapper_open, H5File * file)
Referenced by utilities::Wrapper_o_hdf::add_meta_data_root().