//Copyright 2010 Thomas A Caswell
//tcaswell@uchicago.edu
//http://jfi.uchicago.edu/~tcaswell
//
//This program is free software; you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation; either version 3 of the License, or (at
//your option) any later version.
//
//This program is distributed in the hope that it will be useful, but
//WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
//General Public License for more details.
//
//You should have received a copy of the GNU General Public License
//along with this program; if not, see <http://www.gnu.org/licenses>.
//
//Additional permission under GNU GPL version 3 section 7
//
//If you modify this Program, or any covered work, by linking or
//combining it with MATLAB (or a modified version of that library),
//containing parts covered by the terms of MATLAB User License, the
//licensors of this Program grant you additional permission to convey
//the resulting work.
// 
//If you modify this Program, or any covered work, by linking or
//combining it with IPP (or a modified version of that library),
//containing parts covered by the terms of End User License Agreement
//for the Intel(R) Software Development Products, the licensors of
//this Program grant you additional permission to convey the resulting
//work.
//
//If you modify this Program, or any covered work, by linking or
//combining it with FreeImage (or a modified version of that library),
//containing parts covered by the terms of End User License Agreement
//for FreeImage Public License, the licensors of
//this Program grant you additional permission to convey the resulting
//work.



#ifndef MM_MD_PARSER
#define MM_MD_PARSER
#include <xercesc/util/XercesDefs.hpp>
class fipImage;



XERCES_CPP_NAMESPACE_BEGIN
class DOMNode;

XERCES_CPP_NAMESPACE_END


namespace utilities
{
class Md_store;


/**
   A class for parsing and extracting the meta data from the tiff directories
   of tif files generated by metamorph.  
 */
class Mm_md_parser
{
public:
  Mm_md_parser();
  ~Mm_md_parser();
  Md_store * parse_md(fipImage & img_in) const ;
  
private:
  XMLCh* elm_name_ ;
  XMLCh* key_str_  ;
  XMLCh* type_str_ ;
  XMLCh* value_str_;
  XMLCh* pram_str_ ;


  void parse_elements(XERCES_CPP_NAMESPACE_QUALIFIER DOMNode* pram_elm, Md_store * store)const;
  
  
  
};

}


#endif
